<?php
/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2012 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/

 if ( get_the_author_meta( 'description' ) ) : // If a user has filled out their description, show a bio on their entries  ?>
					<div id="entry-author-info">
						<div id="author-avatar">
							<?php echo get_avatar( get_the_author_meta( 'user_email' ), apply_filters( 'innovate_author_bio_avatar_size', 80 ) ); ?>
						</div><!-- #author-avatar -->
						<div id="author-description">
							<h2><?php printf( __( 'About %s', 'innovate' ), get_the_author() ); ?></h2>
							<p><?php the_author_meta( 'description' ); ?></p>
						</div><!-- #author-description -->
					</div><!-- #entry-author-info -->
<?php endif; ?>