<?php
/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris E Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2013 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/
/**
 * Set the content width based on the theme's design and stylesheet.
 *
 * Used to set the width of images and content. Should be equal to the width the theme
 * is designed for, generally via the style.css stylesheet.
 */

/** Tell WordPress to run innovate_setup() when the 'after_setup_theme' hook is run. */
add_action( 'after_setup_theme', 'innovate_setup' );

if ( ! function_exists( 'innovate_setup' ) ):

 require_once (TEMPLATEPATH . "/premiumwd-options/plugins/theme_plugins.php");
 require_once (TEMPLATEPATH . "/premiumwd-options/shortcodes/shortcodes.php");  
 require_once (TEMPLATEPATH . "/premiumwd-options/widgets/flickr.php");   
 require_once (TEMPLATEPATH . "/premiumwd-options/widgets/twitter.php");  
 require_once (TEMPLATEPATH . "/premiumwd-options/widgets/latest-posts.php");  

 require_once (TEMPLATEPATH . "/premiumwd-options/fonts/main.php");
 require_once (TEMPLATEPATH . "/premiumwd-options/includes/update.php");
 require_once (TEMPLATEPATH . "/premiumwd-options/options-init.php");


function wpex_fix_shortcodes($content){   
    $array = array (
        '<p>[' => '[', 
        ']</p>' => ']', 
        ']<br />' => ']'
    );

    $content = strtr($content, $array);
    return $content;
}
add_filter('the_content', 'wpex_fix_shortcodes');

// Empty search fix
if(!is_admin()){
	add_action('init', 'search_query_fix');
	function search_query_fix(){
		if(isset($_GET['s']) && $_GET['s']==''){
			$_GET['s']=' ';
		}
	}
}


function innovate_setup() {
		add_theme_support( 'post-formats', array( 'aside', 'link', 'gallery', 'status', 'quote', 'image' ) );

	// Produces an avatar image with the hCard-compliant photo class
	function commenter_link() {
    $commenter = get_comment_author_link();
    if ( ereg( '<a[^>]* class=[^>]+>', $commenter ) ) {
        $commenter = ereg_replace( '(<a[^>]* class=[\'"]?)', '\\1url ' , $commenter );
    } else {
        $commenter = ereg_replace( '(<a )/', '\\1class="url "' , $commenter );
    }
    $avatar_email = get_comment_author_email();
    $avatar = str_replace( "class='avatar", "class='photo avatar", get_avatar( $avatar_email, 45 ) );
    echo $avatar . ' <span class="fn n">' . $commenter . '</span>';
	} // end commenter_link

	// Custom callback to list pings
	function custom_pings($comment, $args, $depth) {
       $GLOBALS['comment'] = $comment;
        ?>
            <li id="comment-<?php comment_ID() ?>" <?php comment_class() ?>>
                <div class="comment-author"><?php printf(__('By %1$s on %2$s at %3$s', 'innovate'),
                        get_comment_author_link(),
                        get_comment_date(),
                        get_comment_time() );
                        edit_comment_link(__('Edit', 'innovate'), ' <span class="meta-sep">|</span> <span class="edit-link">', '</span>'); ?></div>
    <?php if ($comment->comment_approved == '0') _e('\t\t\t\t\t<span class="unapproved">Your trackback is awaiting moderation.</span>\n', 'innovate') ?>
            <div class="comment-content">
                <?php comment_text() ?>
            </div>
	<?php } // end custom_pings

	// Custom callback to list comments in the your-theme style
	function custom_comments($comment, $args, $depth) {
	  $GLOBALS['comment'] = $comment;
    $GLOBALS['comment_depth'] = $depth;
 	 ?>
    <li class="<?php
/* Only use the authcomment class from style.css if the user_id is 1 (admin) */
if (1 == $comment->user_id)
$oddcomment = "bypostauthor";
echo $oddcomment;
?>" id="comment-<?php comment_ID() ?>" <?php comment_class() ?>>
    
        <div class="comment-author vcard"><?php commenter_link() ?></div>
        <div class="comment-meta"><?php printf(__('on %1$s at %2$s <span class="meta-sep">|</span> <a href="%3$s" title="Permalink to this comment">Permalink</a>', 'innovate'),
                    get_comment_date(),
                    get_comment_time(),
                    '#comment-' . get_comment_ID() );
                    edit_comment_link(__('Edit', 'innovate'), ' <span class="meta-sep">|</span> <span class="edit-link">', '</span>'); ?></div>
 	 <?php if ($comment->comment_approved == '0') _e("\t\t\t\t\t<span class='unapproved'>Your comment is awaiting moderation.</span>\n", 'innovate') ?>
          <div class="comment-content">
            <?php comment_text() ?>
        </div>
        <?php // echo the comment reply link
            if($args['type'] == 'all' || get_comment_type() == 'comment') :
                comment_reply_link(array_merge($args, array(
                    'reply_text' => __('Reply','innovate'),
                    'login_text' => __('Log in to reply.','innovate'),
                    'depth' => $depth,
                    'before' => '<div class="comment-reply-link">',
                    'after' => '</div>'
                )));
            endif;
        ?>
	<?php } // end custom_comments
        
	add_action('template_redirect', 'single_result');  
    function single_result() {  
        if (is_search()) {  
            global $wp_query;  
            if ($wp_query->post_count == 1) {  
                wp_redirect( get_permalink( $wp_query->posts['0']->ID ) );  
            }  
        }  
    }  

	function diw_post_thumbnail_feeds($content) {   global $post;   if(has_post_thumbnail($post->ID)) {      
	$content = '<div>' . get_the_post_thumbnail($post->ID) . '</div>' . $content;    }   
	return $content;}add_filter('the_excerpt_rss', 'diw_post_thumbnail_feeds');add_filter('the_content_feed', 'diw_post_thumbnail_feeds');  

	// This theme styles the visual editor with editor-style.css to match the theme style.
	add_editor_style();

	// Post Format support. You can also use the legacy "gallery" or "asides" (note the plural) categories.
	add_theme_support( 'post-formats', array( 'aside', 'gallery', 'link', 'image',  'video', 'audio','quote' ) );

	// This theme uses post thumbnails
	add_theme_support( 'post-thumbnails' );  set_post_thumbnail_size( 146, 110, true );  
	
	// additional image sizes
	add_image_size( 'recent-thumbnails', 60, 60, true ); // 60 pixels wide & 60 height
	add_image_size( 'related-posts', 140, 110, true ); // 140 pixels wide & 110 height
	add_image_size( 'related-projects-960', 138, 100, true ); // 128 pixels wide & 105 height
	add_image_size( 'related-projects-1040', 151, 120, true ); // 141 pixels wide & 120 height
	add_image_size( 'related-projects-1120', 165, 130, true ); // 155 pixels wide & 130 height
	add_image_size( 'shortcode-project', 202, 170, true ); // 202 pixels wide & 170 height
	add_image_size( 'shortcode-post', 210, 150, true ); // 210 pixels wide & 150 height
	add_image_size( 'portfolio-single', 650, 450, true ); //450 pixels wide & 450 height
	add_image_size( 'portfolio-2-column', 310, 300, true ); //310 pixels wide & 300 height
	add_image_size( 'portfolio-2-column-960', 450, 300, true ); //450 pixels wide & 300 height
	add_image_size( 'portfolio-2-column-1040', 490, 300, true ); //490 pixels wide & 300 height
	add_image_size( 'portfolio-2-column-1120', 515, 300, true ); //530 pixels wide & 300 height
	add_image_size( 'portfolio-3-column', 200, 150, true ); //200 pixels wide & 150 height
	add_image_size( 'portfolio-3-column-960', 292, 200, true ); //292 pixels wide & 200 height
	add_image_size( 'portfolio-3-column-1040', 314, 200, true ); //314 pixels wide & 200 height
	add_image_size( 'portfolio-3-column-1120', 340, 200, true ); //340 pixels wide & 200 height
	add_image_size( 'portfolio-4-column', 145, 145, true ); //145 pixels wide & 145 height
	add_image_size( 'portfolio-4-column-960', 215, 185, true ); //215 pixels wide & 185 height
	add_image_size( 'portfolio-4-column-1040', 230, 185, true ); //230 pixels wide & 185 height
	add_image_size( 'portfolio-4-column-1120', 250, 185, true ); //250 pixels wide & 185 height
	add_image_size( 'portfolio-5-column-960', 168, 150, true ); //168 pixels wide & 150 height
	add_image_size( 'portfolio-5-column-1040', 180, 150, true ); //180 pixels wide & 150 height
	add_image_size( 'portfolio-5-column-1120', 196, 150, true ); //196 pixels wide & 150 height
	add_image_size( 'portfolio-5-column', 112, 110, true ); //116 pixels wide & 110 height
	add_image_size( 'blog-style', 640, 300, true ); //640 pixels wide & 300 height
	
	// Add default posts and comments RSS feed links to head
	add_theme_support( 'automatic-feed-links' );

	// Make theme available for translation
	// Translations can be filed in the /languages/ directory
	load_theme_textdomain( 'innovate', get_template_directory() . '/languages' );

	$locale = get_locale();
	$locale_file = get_template_directory() . "/languages/$locale.php";
	if ( is_readable( $locale_file ) )
		require_once( $locale_file );

	// This theme uses wp_nav_menu() in one location.
	register_nav_menus( array(
		'primary' => __( 'Primary Navigation', 'innovate' ),
		'secondary' => __( 'Secondary Navigation', 'innovate' ),
	) );

}
endif;

/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * To override this in a child theme, remove the filter and optionally add
 * your own function tied to the wp_page_menu_args filter hook.
 *f
 */
function innovate_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 'innovate_page_menu_args' );

/**
 * Sets the post excerpt length to 40 characters.
 *
 * To override this length in a child theme, remove the filter and add your own
 * function tied to the excerpt_length filter hook.
 *
 * @return int
 */
function innovate_excerpt_length( $length ) {
	return 60;
}
add_filter( 'excerpt_length', 'innovate_excerpt_length' );

function excerpt($limit) {
      $excerpt = explode(' ', get_the_excerpt(), $limit);
      if (count($excerpt)>=$limit) {
        array_pop($excerpt);
        $excerpt = implode(" ",$excerpt).'';
      } else {
        $excerpt = implode(" ",$excerpt);
      } 
      $excerpt = preg_replace('`\[[^\]]*\]`','',$excerpt);
      return $excerpt;
    }

    function content($limit) {
      $content = explode(' ', get_the_content(), $limit);
      if (count($content)>=$limit) {
        array_pop($content);
        $content = implode(" ",$content).'';
      } else {
        $content = implode(" ",$content);
      } 
      $content = preg_replace('/\[.+\]/','', $content);
      $content = apply_filters('the_content', $content); 
      $content = str_replace(']]>', ']]&gt;', $content);
      return $content;
    }
/**
 * Custom style declarations
 *
 * Outputs CSS declarations generated by theme options
 * and custom user defined CSS in the document <head>
 *
 */
if ( ! function_exists( 'premiumwd_custom_styles' ) ) : function premiumwd_custom_styles() { ?>


<style type="text/css" media="screen">
<?php if (get_option('premiumwd_width') == '960px') : ?>#header, #main, #wrapper { max-width: 960px;}.flickr_widget ul li img{width:50px;height:46px;} .flickr_widget ul li{width:56px;height:56px;}#portfolio-list {max-width:920px;}.jcarousel-skin-tango li.slide, .jcarousel-skin-tango li.jcarousel-item, .jcarousel-skin-tango li .gallery-slider ul.slides li, .jcarousel-skin-tango li .gallery-slider, .jcarousel-skin-tango li .gallery-slider ul.slides, .jcarousel-skin-tango li .recent-posts, ul.project-item li, .jcarousel-skin-tango li img, ul.post-lists li iframe {width:172px !important;}
ul#relatedprojects{max-width:900px;}ul.post-list li, ul.post-list li img{max-width:210px;}.entry-content .flickr_widget ul li:nth-child(3n) {margin-right:0px !important;}#nav-below{max-width:920px;}#post-column {max-width:219px;}.entry-content-2, .entry-content-3, .entry-content-4, #content .entry-title, .bottom-wrapper{max-width:960px;} #footer-widget-area #first {width:160px;} #footer-widget-area .widget-area {width:202px;}#colophon,#bottom-wrapper {max-width:960px;}#row,.breadcrumb {max-width:960px;}.box, .entry-summary{max-width:960px;}.entry-content{max-width:960px;}.widget_rcp_recent_custom_posts img {height: 40px;max-width: 40px;}<?php endif; ?>
<?php if (get_option('premiumwd_width') == '1040px') : ?>.flickr_widget ul li img{width:54px;height:50px;} .flickr_widget ul li{width:60px;height:60px;}#portfolio-list {max-width:1000px;}.jcarousel-skin-tango li.slide, .jcarousel-skin-tango li.jcarousel-item, .jcarousel-skin-tango li .gallery-slider ul.slides li, .jcarousel-skin-tango li .gallery-slider, .jcarousel-skin-tango li .gallery-slider ul.slides, .jcarousel-skin-tango li .recent-posts, ul.project-item li, .jcarousel-skin-tango li img, ul.post-lists li iframe {width:188px !important;}
ul#relatedprojects{max-width:980px;}ul.post-list li, ul.post-list li img{max-width:228px;}#nav-below{max-width:1000px;}.entry-content .flickr_widget ul li:nth-child(4n) {margin-right:0px !important;}#post-column {max-width:289px;}.entry-content-2, .entry-content-3, .entry-content-4, #content .entry-title, .bottom-wrapper{max-width:1040px;}
#footer-widget-area #first {width:200px;}#footer-widget-area .widget-area {width:220px;}#colophon,#bottom-wrapper {max-width:1040px;}#row,.breadcrumb {max-width:1040px;}#header, #main, #wrapper { max-width: 1040px ;}.box, .entry-summary{max-width:1040px;}.entry-content{max-width:1040px;}.widget_rcp_recent_custom_posts img {height: 50px;max-width: 50px;}<?php endif; ?>
<?php if (get_option('premiumwd_width') == '1120px') : ?>.flickr_widget ul li img{width:58px;height:54px;} .flickr_widget ul li{width:64px;height:64px;}#portfolio-list{max-width:1080px;}.jcarousel-skin-tango li.slide, .jcarousel-skin-tango li.jcarousel-item, .jcarousel-skin-tango li .gallery-slider ul.slides li, .jcarousel-skin-tango li .gallery-slider, .jcarousel-skin-tango li .gallery-slider ul.slides, .jcarousel-skin-tango li .recent-posts, ul.project-item li, .jcarousel-skin-tango li img, ul.post-lists li iframe {width:204px !important;}
ul#relatedprojects{max-width:1120px;}ul.post-list li, ul.post-list li img {max-width:247px;}#nav-below{max-width:1080px;}
.entry-content #third .flickr_widget ul li:nth-child(5n),.entry-content #secondary .flickr_widget ul li:nth-child(5n) {margin-right:0px !important;}#post-column {max-width:370px;}.entry-content-2, .entry-content-3, .entry-content-4, #content .entry-title, .bottom-wrapper {max-width:1120px;}#footer-widget-area #first {width:228px;} #footer-widget-area .widget-area {width:235px;}#colophon,#bottom-wrapper {max-width:1120px;}#row,.breadcrumb {max-width:1120px;}#header, #main, #wrapper { max-width: 1120px ;}.box,  .entry-summary{max-width:1120px;}.entry-content{max-width:1120px;}.widget_rcp_recent_custom_posts img {height: 60px;max-width: 60px;}<?php endif; ?>
<?php if (get_option('premiumwd_layout') == 'Boxed') : ?>#header{border-bottom:0px none;} .slider,#featured img{max-width:auto!important;}#footer{border-bottom-right-radius:0px;border-bottom-left-radius:0px;}#main, #header {-moz-box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.3), 0 0 3px rgba(0, 0, 0, 0.2);-webkit-box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.3), 0 0 3px rgba(0, 0, 0, 0.2); box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.3), 0 0 3px rgba(0, 0, 0, 0.2);}.entry-content-3, .entry-content-4, .single-project .entry-content {box-shadow: 0 2px 0 0 #F7F7F7 inset;background: #fdfdfd;}#header{max-width:auto;}
<?php endif; ?>
<?php if (get_option('premiumwd_layout') == 'Wide') : ?>#header{-moz-box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.1), 0 0 3px rgba(0, 0, 0, 0.1);-webkit-box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.1), 0 0 3px rgba(0, 0, 0, 0.1); box-shadow: 0 5px 3px -10px rgba(0, 0, 0, 0.1), 0 0 3px rgba(0, 0, 0, 0.1);border-bottom:1px solid #DEDEDE;} #header-top{margin:0px 30px;} #wrapper{margin:0px !important;}#header,#footer{border-radius:0px;}#header, #main{margin:0px;box-shadow:none;}.style-wrapper {background: none;border: none;box-shadow: none;margin: 0px;padding: 0px;}.slider,#featured img{width:100% !important;}#entry-content #primary, #entry-content #secondary, #entry-content #third, .entry-content{background:none;box-shadow: none;}#main{margin-top:0px;}.entry-content-3, .entry-content-4, .single-project .entry-content {box-shadow: none;background: #fff;} #entry-title{background: #FCFCFC;border-bottom: 1px solid #E8E8E8;border-top: 1px solid #E8E8E8;box-shadow: 0 2px 0 0 #F7F7F7 inset, 0 -2px 0 0 #F7F7F7 inset;}<?php endif; ?>
<?php if (get_option('premiumwd_allow_scroll') == 'true'): ?>#header {width:100%;}#main{padding-top:69px;}<?php endif; ?>
<?php if (get_option('premiumwd_allow_scroll') == 'false'): ?>#header {position:relative !important;}#layerslider-wrapper{padding-top:0px !important;}<?php endif; ?>
</style>

<style type="text/css" media="screen">
#access ul.sub-menu li a{font-size:<?php echo get_option('sub_menu_fontsize'); ?>; font-family: <?php echo get_option('sub_menu_fontfamily'); ?>;}
.entry-content a:link, .entry-content a:visited, #nav-below a:link, #nav-below a:visited, a:link, a:visited {color: #<?php echo get_option('main_links_color');?>;}
.entry-content a:active, .entry-summary a:active, .entry-content a:hover, .entry-summary a:hover, #nav-below a:hover, a:hover {color: #<?php echo get_option('main_links_hover_color');?>;}
#footer a:link, #footer a:active, #footer a:visited, #site-info .sub-menu ul li a:link, #site-info .sub-menu ul li a:active, #site-info .sub-menu ul li a:visited  {color: #<?php echo get_option('footer_links_color');?> !important;}
#footer a:hover, #site-info .sub-menu ul li a:hover {color: #<?php echo get_option('footer_links_hover');?> !important;}
* html #access ul li a:hover {color: #<?php echo get_option('header_menu_active_color');?>;}
#access a:link, #access a:visited, #access li a:link, #access li a:visited {color: #<?php echo get_option('header_menu_link_color');?>;}
#access a:active, #access a:hover, #access li a:active, #access li a:hover {color: #<?php echo get_option('header_menu_hover_color');?>;}
#access ul.sub-menu li a{color: #<?php echo get_option('sub_header_menu_link_color');?>; } 
#access ul.sub-menu li a:hover{color: #<?php echo get_option('sub_header_menu_hover');?>; }
#footer {color:#<?php echo get_option('footer_text_color'); ?>;}
.post-content {color: #<?php echo get_option('main_body_text_color');?>;}
#site-title {font-size:<?php echo get_option('logo_fontsize'); ?>; font-family: <?php echo get_option('logo_fontfamily'); ?>;}
#access .menu-header, div.menu  {font-size:<?php echo get_option('header_menu_fontsize'); ?>; font-family: <?php echo get_option('header_menu_fontfamily'); ?>;}
#content .page-title {font-size:<?php echo get_option('header_title_fontsize'); ?>; font-family: <?php echo get_option('header_title_fontfamily'); ?>; color: #<?php echo get_option('header_title_fontcolor'); ?>;}
.entry-content #secondary .widget-title, .entry-content #third .widget-title, .entry-content-2 #secondary .widget-title, .entry-content-2 #third .widget-title, .entry-content-3 #secondary .widget-title, .entry-content-3 #third .widget-title, .entry-content-4 #secondary .widget-title, .entry-content-4 #third .widget-title {font-size:<?php echo get_option('sidebar_title_fontsize'); ?>; font-family: <?php echo get_option('sidebar_title_fontfamily'); ?>; color: #<?php echo get_option('sidebar_title_fontcolor'); ?>;}
#relatedposts h4 {font-size:<?php echo get_option('related_posts_fontsize'); ?>; font-family: <?php echo get_option('related_posts_fontfamily'); ?>;}
.navigation {font-size:<?php echo get_option('pagination_fontsize'); ?>; font-family: <?php echo get_option('pagination_fontfamily'); ?>; }
.footer-bubble {background:#<?php echo get_option('widget_background_color'); ?>;}
#footer {background-color:#<?php echo get_option('footer_background_color');?>; }
#footer-widget-area .widget-title {font-size:<?php echo get_option('footer_title_fontsize'); ?>; font-family: <?php echo get_option('footer_title_fontfamily'); ?>; }
#main .widget-area .textwidget, #twitter_update_list {color: #<?php echo get_option('footer_content_fontcolor'); ?>;font-size:<?php echo get_option('footer_content_fontsize'); ?>; font-family: <?php echo get_option('footer_content_fontfamily'); ?>; }
.bottom-two-half {font-size:<?php echo get_option('footer_menu_fontsize'); ?>; font-family: <?php echo get_option('footer_menu_fontfamily'); ?>;}
.bottom-one-half{font-size:<?php echo get_option('copyright_fontsize'); ?>; font-family: <?php echo get_option('copyright_fontfamily'); ?>; }
#footer-widget-area .widget-title {color: #<?php echo get_option('footer_title_fontcolor'); ?>;}
#relatedposts h4 { color: #<?php echo get_option('related_posts_fontcolor'); ?>;}
#site-info {color: #<?php echo get_option('copyright_fontcolor'); ?>;}
#header {background-color: #<?php echo get_option('header_background_color'); ?>;}
#nivo-full {background-color: #<?php echo get_option('nivo_slider_color'); ?>;}
#box, #entry-content, #entry-summary, .box {background-color: #<?php echo get_option('body_background_color'); ?>;}
#access ul ul a {background-color: #<?php echo get_option('drop_down_background_color'); ?>;}
.comment-title, #access ul.sub-menu li {border-bottom:1px solid #<?php echo get_option('lines_border_color'); ?>}
hr {border:1px solid #<?php echo get_option('lines_border_color'); ?>}
.respond {border-top:1px solid #<?php echo get_option('lines_border_color'); ?>}
#access ul ul.sub-menu {background-color: #fff;}
#access ul ul ul.sub-menu {background-color: #fff;}
#access ul li ul li ul.sub-menu {background-color: #fff;}
</style>

<?php } endif;
 add_action( 'wp_head', 'premiumwd_custom_styles' ); 


/**
 * Remove inline styles printed when the gallery shortcode is used.
 *
 * Galleries are styled by the theme in Twenty Ten's style.css. This is just
 * a simple filter call that tells WordPress to not use the default styles.
 *
 */
add_filter( 'use_default_gallery_style', '__return_false' );

/**
 * Deprecated way to remove inline styles printed when the gallery shortcode is used.
 *
 * This function is no longer needed or used. Use the use_default_gallery_style
 * filter instead, as seen above.
 *
 * @deprecated Deprecated in Twenty Ten 1.2 for WordPress 3.1
 *
 * @return string The gallery style filter, with the styles themselves removed.
 */
function innovate_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
// Backwards compatibility with WordPress 3.0.
if ( version_compare( $GLOBALS['wp_version'], '3.1', '<' ) )
	add_filter( 'gallery_style', 'innovate_remove_gallery_css' );

if ( ! function_exists( 'innovate_comment' ) ) :
/**
 * Template for comments and pingbacks.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own innovate_comment(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 */
function innovate_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case '' :
	?>
	<li <?php comment_class(); ?> id="li-comment-<?php comment_ID(); ?>">
		<div id="comment-<?php comment_ID(); ?>">
		<div class="comment-author vcard">
			<?php echo get_avatar( $comment, 40 ); ?>
			<?php printf( __( '%s <span class="says">says:</span>', 'innovate' ), sprintf( '<cite class="fn">%s</cite>', get_comment_author_link() ) ); ?>
		</div><!-- .comment-author .vcard -->
		<?php if ( $comment->comment_approved == '0' ) : ?>
			<em class="comment-awaiting-moderation"><?php _e( 'Your comment is awaiting moderation.', 'innovate' ); ?></em>
			<br />
		<?php endif; ?>

		<div class="comment-meta commentmetadata"><a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>">
			<?php
				/* translators: 1: date, 2: time */
				printf( __( '%1$s at %2$s', 'innovate' ), get_comment_date(),  get_comment_time() ); ?></a><?php edit_comment_link( __( '(Edit)', 'innovate' ), ' ' );
			?>
		</div><!-- .comment-meta .commentmetadata -->

		<div class="comment-body"><?php comment_text(); ?></div>

		<div class="reply">
			<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
		</div><!-- .reply -->
	</div><!-- #comment-##  -->

	<?php
			break;
		case 'pingback'  :
		case 'trackback' :
	?>
<li class="post pingback">
		<p><?php _e( 'Pingback:', 'innovate' ); ?> <?php comment_author_link(); ?><?php edit_comment_link( __( '(Edit)', 'innovate' ), ' ' ); ?></p>
	<?php
			break;
	endswitch;
}
endif;

/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 *
 * To override innovate_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @uses register_sidebar
 */
function innovate_widgets_init() {
	
	// Area 1, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Main Widget Area', 'innovate' ),
		'id' => 'main-widget-area',
		'description' => __( 'The main widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );
	
	// Area 2, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Contact Widget Area', 'innovate' ),
		'id' => 'contact-widget-area',
		'description' => __( 'The contact widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );

	// Area 3, located below the Primary Widget Area in the sidebar. Empty by default.
	register_sidebar( array(
		'name' => __( 'Blog Widget Area', 'innovate' ),
		'id' => 'blog-widget-area',
		'description' => __( 'The blog widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );
	
	// Area 4, located below the Primary Widget Area in the sidebar. Empty by default.
	register_sidebar( array(
		'name' => __( 'Portfolio Widget Area', 'innovate' ),
		'id' => 'portfolio-widget-area',
		'description' => __( 'The portfolio widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );
	
	// Area 5, located in the sitemap sidebar. Empty by default.
	register_sidebar( array(
		'name' => __( 'Sitemap Widget Area', 'innovate' ),
		'id' => 'sitemap-widget-area',
		'description' => __( 'The Sitemap widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );
	
	// Area 6, located in the page sidebar. Empty by default.
	register_sidebar( array(
		'name' => __( 'Page Widget Area', 'innovate' ),
		'id' => 'page-widget-area',
		'description' => __( 'The Page widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<div class="headline"><h3 class="widget-title">',
		'after_title' => '</h3></div>',
	) );
	
	// Area 7, located in the footer. Empty by default.
	register_sidebar( array(
		'name' => __( 'First Footer Widget Area', 'innovate' ),
		'id' => 'first-footer-widget-area',
		'description' => __( 'The first footer widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );

	// Area 8, located in the footer. Empty by default.
	register_sidebar( array(
		'name' => __( 'Second Footer Widget Area', 'innovate' ),
		'id' => 'second-footer-widget-area',
		'description' => __( 'The second footer widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );

	// Area 9, located in the footer. Empty by default.
	register_sidebar( array(
		'name' => __( 'Third Footer Widget Area', 'innovate' ),
		'id' => 'third-footer-widget-area',
		'description' => __( 'The third footer widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );

	// Area 10, located in the footer. Empty by default.
	register_sidebar( array(
		'name' => __( 'Fourth Footer Widget Area', 'innovate' ),
		'id' => 'fourth-footer-widget-area',
		'description' => __( 'The fourth footer widget area', 'innovate' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	) );
	

}
/** Register sidebars by running innovate_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'innovate_widgets_init' );

/**
 * Removes the default styles that are packaged with the Recent Comments widget.
 *
 * To override this in a child theme, remove the filter and optionally add your own
 * function tied to the widgets_init action hook.
 *
 * This function uses a filter (show_recent_comments_widget_style) new in WordPress 3.1
 * to remove the default style. Using Twenty Ten 1.2 in WordPress 3.0 will show the styles,
 * but they won't have any effect on the widget in default Twenty Ten styling.
 *
 */
function innovate_remove_recent_comments_style() {
	add_filter( 'show_recent_comments_widget_style', '__return_false' );
}
add_action( 'widgets_init', 'innovate_remove_recent_comments_style' );

if ( ! function_exists( 'innovate_posted_on' ) ) :
/**
 * Prints HTML with meta information for the current post-date/time and author.
 *
 */
function innovate_posted_on() {
	printf( __( '<span class="%1$s">Posted on</span> %2$s <span class="meta-sep">by</span> %3$s', 'innovate' ),
		'meta-prep meta-prep-author',
		sprintf( '<a href="%1$s" title="%2$s" rel="bookmark"><span class="entry-date">%3$s</span></a>',
			get_permalink(),
			esc_attr( get_the_time() ),
			get_the_date()
		),
		sprintf( '<span class="author vcard"><a class="url fn n" href="%1$s" title="%2$s">%3$s</a></span>',
			get_author_posts_url( get_the_author_meta( 'ID' ) ),
			esc_attr( sprintf( __( 'View all posts by %s', 'innovate' ), get_the_author() ) ),
			get_the_author()
		)
	);
}
endif;

if ( ! function_exists( 'innovate_posted_in' ) ) :
/**
 * Prints HTML with meta information for the current post (category, tags and permalink).
 *
 */
function innovate_posted_in() {
	// Retrieves tag list of current post, separated by commas.
	$tag_list = get_the_tag_list( '', ', ' );
	if ( $tag_list ) {
		$posted_in = __( 'This entry was posted in %1$s and tagged %2$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'innovate' );
	} elseif ( is_object_in_taxonomy( get_post_type(), 'category' ) ) {
		$posted_in = __( 'This entry was posted in %1$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'innovate' );
	} else {
		$posted_in = __( 'Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'innovate' );
	}
	// Prints the string, replacing the placeholders.
	printf(
		$posted_in,
		get_the_category_list( ', ' ),
		$tag_list,
		get_permalink(),
		the_title_attribute( 'echo=0' )
	);
}
endif;


// Portfolio - Projects
add_action('init', 'project_custom_init');    
      
    /*-- Custom Post Init Begin --*/  
    function project_custom_init()  
    {  
      $labels = array(  
        'name' => _x('Projects', 'post type general name'),  
        'singular_name' => _x('Project', 'post type singular name'),  
        'add_new' => _x('Add New', 'project'),  
        'add_new_item' => __('Add New Project'),  
        'edit_item' => __('Edit Project'),  
        'new_item' => __('New Project'),  
        'view_item' => __('View Project'),  
        'search_items' => __('Search Projects'),  
        'not_found' =>  __('No projects found'),  
        'not_found_in_trash' => __('No projects found in Trash'),  
        'parent_item_colon' => '',  
        'menu_name' => 'Projects'  
      
      );  
        
     $args = array(  
        'labels' => $labels,  
        'public' => true,  
        'publicly_queryable' => true,  
        'show_ui' => true,  
        'show_in_menu' => true,  
        'query_var' => true,  
        'rewrite' => true,  
        'capability_type' => 'post',  
        'has_archive' => true,  
        'hierarchical' => false,  
        'menu_position' => null,  
        'supports' => array('title','editor','author','thumbnail','comments')  
      );  
      // The following is the main step where we register the post.  
      register_post_type('project',$args);  
      flush_rewrite_rules();  
      // Initialize New Taxonomy Labels  
      $labels = array(  
        'name' => _x( 'Tags', 'taxonomy general name' ),  
        'singular_name' => _x( 'Tag', 'taxonomy singular name' ),  
        'search_items' =>  __( 'Search Types' ),  
        'all_items' => __( 'All Tags' ),  
        'parent_item' => __( 'Parent Tag' ),  
        'parent_item_colon' => __( 'Parent Tag:' ),  
        'edit_item' => __( 'Edit Tags' ),  
        'update_item' => __( 'Update Tag' ),  
        'add_new_item' => __( 'Add New Tag' ),  
        'new_item_name' => __( 'New Tag Name' ),  
      );  
        // Custom taxonomy for Project Tags  
        register_taxonomy('tagportfolio',array('project'), array(  
        'hierarchical' => true,  
        'labels' => $labels,  
        'show_ui' => true,  
        'query_var' => true,  
        'rewrite' => array( 'slug' => 'tag-portfolio' ),  
      ));  
        
    }  
    /*-- Custom Post Init Ends --*/  

/*--- Custom Messages - project_updated_messages ---*/  
    add_filter('post_updated_messages', 'project_updated_messages');  
      
    function project_updated_messages( $messages ) {  
      global $post, $post_ID;  
      
      $messages['project'] = array(  
        0 => '', // Unused. Messages start at index 1.  
        1 => sprintf( __('Project updated. <a href="%s">View project</a>'), esc_url( get_permalink($post_ID) ) ),  
        2 => __('Custom field updated.'),  
        3 => __('Custom field deleted.'),  
        4 => __('Project updated.'),  
        /* translators: %s: date and time of the revision */  
        5 => isset($_GET['revision']) ? sprintf( __('Project restored to revision from %s'), wp_post_revision_title( (int) $_GET['revision'], false ) ) : false,  
        6 => sprintf( __('Project published. <a href="%s">View project</a>'), esc_url( get_permalink($post_ID) ) ),  
        7 => __('Project saved.'),  
        8 => sprintf( __('Project submitted. <a target="_blank" href="%s">Preview project</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),  
        9 => sprintf( __('Project scheduled for: <strong>%1$s</strong>. <a target="_blank" href="%2$s">Preview project</a>'),  
          // translators: Publish box date format, see http://php.net/date  
          date_i18n( __( 'M j, Y @ G:i' ), strtotime( $post->post_date ) ), esc_url( get_permalink($post_ID) ) ),  
        10 => sprintf( __('Project draft updated. <a target="_blank" href="%s">Preview project</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),  
      );  
      
      return $messages;  
    }  
      
    /*--- #end SECTION - project_updated_messages ---*/  
	
	/*--- Demo URL meta box ---*/  
      
    add_action('admin_init','portfolio_meta_init');  
      
    function portfolio_meta_init()  
    {  
        // add a meta box for WordPress 'project' type  
        add_meta_box('portfolio_meta', 'Project Info', 'portfolio_meta_setup', 'project', 'side', 'low');  
       
        // add a callback function to save any data a user enters in  
        add_action('save_post','portfolio_meta_save');  
    }  
      
    function portfolio_meta_setup()  
    {  
        global $post;  
           
        ?>  
            <div class="portfolio_meta_control">  
                <label>Sub-Heading</label>  
                <p>  
                    <input type="text" name="sub-heading" value="<?php echo get_post_meta($post->ID,'sub-heading',TRUE); ?>" style="max-width: 100%;" />  
                </p> 
            </div>  
        <?php  
      
        // create for validation  
        echo '<input type="hidden" name="meta_noncename" value="' . wp_create_nonce(__FILE__) . '" />';  
    }  
      
    function portfolio_meta_save($post_id)   
    {  
        // check nonce  
        if (!isset($_POST['meta_noncename']) || !wp_verify_nonce($_POST['meta_noncename'], __FILE__)) {  
        return $post_id;  
        }  
      
        // check capabilities  
        if ('post' == $_POST['post_type']) {  
        if (!current_user_can('edit_post', $post_id)) {  
        return $post_id;  
        }  
        } elseif (!current_user_can('edit_page', $post_id)) {  
        return $post_id;  
        }  
      
        // exit on autosave  
        if (defined('DOING_AUTOSAVE') == DOING_AUTOSAVE) {  
        return $post_id;  
        }  
      
        if(isset($_POST['sub-heading']))   
        {  
            update_post_meta($post_id, 'sub-heading', $_POST['sub-heading']);  
        } else   
        {  
            delete_post_meta($post_id, 'sub-heading');  
        }  
    }  
      
    /*--- #end  Demo URL meta box ---*/  
	
function enqueue_filterable()  
{  
    wp_register_script( 'filterable', get_template_directory_uri() . '/js/filterable.js', array( 'jquery' ) );  
    wp_enqueue_script( 'filterable' );  
	
}  
add_action('wp_enqueue_scripts', 'enqueue_filterable'); 

function admin_localize_scripts(){
	
	wp_localize_script('jquery', 'PremiumShortcodes', array('template_directory' => get_template_directory_uri() ));
	
}

add_action('admin_enqueue_scripts' , 'admin_localize_scripts');
/*--- shortcode tinymce ---*/
function tcustom_addbuttons() {
    if ( ! current_user_can('edit_posts') && ! current_user_can('edit_pages') )
        return;
    if ( get_user_option('rich_editing') == 'true') {
        add_filter("mce_external_plugins", "add_tcustom_tinymce_plugin");
        add_filter('mce_buttons', 'register_tcustom_button');
    }
}
function register_tcustom_button($buttons) {
    array_push($buttons, "|", "shortcodes");
    return $buttons;
} 
function add_tcustom_tinymce_plugin($plugin_array) {

    $plugin_array['shortcodes'] = get_bloginfo('home').'/wp-content/themes/innovate/premiumwd-options/tinymce/editor_plugin.js';

    return $plugin_array;

}

// init process for button control

add_action('init', 'tcustom_addbuttons');

function new_excerpt_more($more) {
       global $post;
	return '.';
}
add_filter('excerpt_more', 'new_excerpt_more');


function gallery_first_image(){		

	global $post;

	$args = array(
		'post_type'   => 'attachment',
		'numberposts' => 3,
		'post_parent' => $post->ID,
		'order' => 'ASC',
		'orderby' => 'menu_order',
		'post_mime_type' => 'image'
		
		);

	$attachments = get_posts( $args );

	if ( $attachments )
	{
		foreach ( $attachments as $attachment )
		{					
			$img[] = wp_get_attachment_url( $attachment->ID ); 
		}
	}		
	return $img;	
}

// Theme Options Tab
function theme_options_link() {
global $wp_admin_bar, $wpdb;
if ( !is_super_admin() || !is_admin_bar_showing() )
return;
$wp_admin_bar->add_menu( array( 'parent' => 'appearance', 'title' => __( 'Theme Options', 'innovate' ), 'href' => get_bloginfo('url').'/wp-admin/admin.php?page=premiumwd_theme_options' ) );
}
add_action('admin_bar_menu', 'theme_options_link', 1000);

// Pagination
function pagination($pages = '', $range = 2)
{  
     $showitems = ($range * 2)+1;  

     global $paged;
     if(empty($paged)) $paged = 1;

     if($pages == '')
     {
         global $wp_query;
         $pages = $wp_query->max_num_pages;
         if(!$pages)
         {
             $pages = 1;
         }
     }   

     if(1 != $pages)
     {
         echo "<div class=\"pagination\"><span>Page ".$paged." of ".$pages."</span>";
         if($paged > 2 && $paged > $range+1 && $showitems < $pages) echo "<a href='".get_pagenum_link(1)."'>&laquo; First</a>";
         if($paged > 1 && $showitems < $pages) echo "<a href='".get_pagenum_link($paged - 1)."'>&lsaquo; Previous</a>";

         for ($i=1; $i <= $pages; $i++)
         {
             if (1 != $pages &&( !($i >= $paged+$range+1 || $i <= $paged-$range-1) || $pages <= $showitems ))
             {
                 echo ($paged == $i)? "<span class=\"current\">".$i."</span>":"<a href='".get_pagenum_link($i)."' class=\"inactive\">".$i."</a>";
             }
         }

         if ($paged < $pages && $showitems < $pages) echo "<a href=\"".get_pagenum_link($paged + 1)."\">Next &rsaquo;</a>";  
         if ($paged < $pages-1 &&  $paged+$range-1 < $pages && $showitems < $pages) echo "<a href='".get_pagenum_link($pages)."'>Last &raquo;</a>";
         echo "</div>\n";
     }
}


//*Add nav-arrows to navigation if parent
class premium_Walker_Nav_Menu extends Walker_Nav_Menu {
     function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
        global $wp_query;
        $indent = ( $depth ) ? str_repeat( "\t", $depth ) : '';

        $class_names = '';

        $classes = empty( $item->classes ) ? array() : (array) $item->classes;
        $classes[] = 'menu-item-' . $item->ID;

        $class_names = join( ' ', apply_filters( 'nav_menu_css_class', array_filter( $classes ), $item, $args ) );
        $class_names = $class_names ? ' class="' . esc_attr( $class_names ) . '"' : '';

        $id = apply_filters( 'nav_menu_item_id', 'menu-item-'. $item->ID, $item, $args );
        $id = $id ? ' id="' . esc_attr( $id ) . '"' : '';

        $output .= $indent . '<li' . $id . $class_names .'>';

        $attributes  = ! empty( $item->attr_title ) ? ' title="'  . esc_attr( $item->attr_title ) .'"' : '';
        $attributes .= ! empty( $item->target )     ? ' target="' . esc_attr( $item->target     ) .'"' : '';
        $attributes .= ! empty( $item->xfn )        ? ' rel="'    . esc_attr( $item->xfn        ) .'"' : '';
        $attributes .= ! empty( $item->url )        ? ' href="'   . esc_attr( $item->url        ) .'"' : '';

        $item_output = $args->before;
        $item_output .= '<a'. $attributes .'>';
        $item_output .= $args->link_before . apply_filters( 'the_title', $item->title, $item->ID ) . $args->link_after;

        if ( 'primary' == $args->theme_location ) {
            $submenus = 0 == $depth || 1 == $depth ? get_posts( array( 'post_type' => 'nav_menu_item', 'numberposts' => 1, 'meta_query' => array( array( 'key' => '_menu_item_menu_item_parent', 'value' => $item->ID, 'fields' => 'ids' ) ) ) ) : false;
            $item_output .= ! empty( $submenus ) ? ( 0 == $depth ? '<span class="arrow">&#x25BE;</span>' : '<span class="sub-arrow">&#x25B8;</span>' ) : '';
        }
        $item_output .= '</a>';
        $item_output .= $args->after;

        $output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
    }
}

//*Gallery shortcode +fancybox
remove_shortcode( 'gallery' );
function gallery_filter( $atts, $content = null ) {
	 static $output, $args;
	 $output = '';
	 

		$output .= '<link rel="stylesheet" href="'. get_bloginfo( 'template_directory' ) .'/css/jquery.fancybox.css" type="text/css" media="screen" />
    <script defer type="text/javascript" src="'. get_bloginfo( 'template_directory' ) .'/js/jquery.fancybox.pack.js"></script>
    <script defer type="text/javascript" src="'. get_bloginfo( 'template_directory' ) .'/js/fancybox-init.js"></script><script defer type="text/javascript" src="'. get_bloginfo( 'template_directory' ) .'/js/jquery.mousewheel-3.0.4.pack.js"></script>
<script defer type="text/javascript" src="'. get_bloginfo( 'template_directory' ) .'/js/jquery.flexslider.js"></script><link rel="stylesheet" href="'. get_bloginfo( 'template_directory' ) .'/css/flexslider.css" type="text/css" media="screen" />
';
		$output .= '
		<script type="text/javascript">
  jQuery(document).ready(function() {
  jQuery(".flexslider").flexslider({
    animation: "slide",
	animationLoop: false,
	slideshowSpeed: 7000,      
	animationSpeed: 600,
	controlNav: true,
	directionNav: true
  });
});
</script>';


$output .= "<div class='flexslider' style='margin-bottom:10px;'><ul class='slides'>";

  $attachments = get_posts( $args );
$image_url = gallery_first_image(); if($image_url) { foreach($image_url as $i) :
						
			 $output .= "<li>";
            $output .= "<a class='fancybox' rel='gallery1' href='".$i."' title='". get_the_title()."'>";
            $output .= "<img width='639px' height='300px' src='".$i."' />";
            $output .= "</a>";
             $output .= "</li>";  
			
              endforeach; }
			   	    
             $output .= " </ul></div>";
  
  return $output;
 
  }
add_shortcode( 'gallery' , 'gallery_filter' );


/**
 * add ie conditional html5 shim to header
 */
function add_ie_html5_shim () {
    echo '<!--[if lt IE 9]>';
    echo '<script src="'. get_template_directory_uri() .'/js/html5.js"></script>';
    echo '<![endif]-->';
}
add_action('wp_head', 'add_ie_html5_shim');	

/**
 * add ie 6-8 conditional selectivizr to header
 * Important for the responsive framework
 */
function add_ie_selectivizr () {
    echo '<!--[if (gte IE 6)&(lte IE 8)]>';
    echo '<script src="'. get_template_directory_uri() .'/js/selectivizr-min.js"></script>';
    echo '<![endif]-->';
}
add_action('wp_head', 'add_ie_selectivizr');


/**
 * Breadcrumb
 *
 */
function the_breadcrumb() {
	global $post;
	echo '<nav id="breadcrumbs"><ul>';
	if (!is_home()) {
		echo '<a href="';
		echo get_option('home');
		echo '">';
		bloginfo('name');
		echo "</a> › ";
		if (is_category() || is_single() || is_tax()) {
			if('is_category'){
				$category = get_the_category($post->ID); 
				$cat_link = get_category_link( $category[0]->term_id );
				if(!empty($category[0]->cat_name)){
					echo '<a href="'.$cat_link.'">'.$category[0]->cat_name.'</a>';
				}else{
					echo '<a href="';
					echo get_option('home');
					echo '/project">';
					echo 'Projects';
					echo '</a>';
				}
			}
			if (is_single()) {
				echo " › ";
				the_title();
			}
		} elseif (is_page()) {
			echo the_title();
		}
		elseif (is_tag()) {single_tag_title();}
        elseif (is_day()) {echo"Archive for "; the_time('F jS, Y');}
        elseif (is_month()) {echo"Archive for "; the_time('F, Y');}
        elseif (is_year()) {echo"Archive for "; the_time('Y');}
        elseif (is_author()) {echo"Author Archive";}
        elseif (isset($_GET['paged']) && !empty($_GET['paged'])) {echo "Blog Archives";}
        elseif (is_search()) {echo"Search Results";}
	}echo '</ul></nav>';
}
add_action('init' , 'send_mail_action',10,99);
function send_mail_action(){
	if(isset($_GET['action']) && $_GET['action'] == 'sendmail'){
		include('premiumwd-options/sendmail.php');
		echo send_mail_func();
		die();
	}
}		