<?php
/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2012 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/

 	
	/*	Get google webfonts from provided json file (downloaded at 28-04-2013)
	 *	===========================================================================*/
		
	function get_google_webfonts(){
		
		$file = get_template_directory() . '/premiumwd-options/fonts/google-webfonts.json';

		if(file_exists( $file )){

			$jsonObj = json_decode( file_get_contents( $file ), true );
			
			if( $jsonObj ){
				
				$arr_font = array(
					'Arial' => 'Arial',
					'Courier' => 'Courier',
					'Georgia' => 'Georgia',
					'Impact' => 'Impact',
					'Lucida' => 'Lucida',
					'Lucida Console' => 'Lucida Console',
					'Tahoma' => 'Tahoma',
					'Times New Roman' => 'Times New Roman',
					'Trebuchet' => 'Trebuchet',
					'Verdana' => 'Verdana'
				);
				
				foreach( $jsonObj['items'] as $font )
					$arr_font[$font['family']] = $font['family'];
				
				return $arr_font;
			}			
		}
		
		return null;			
	}
	
	$fonts_array = get_google_webfonts();
		   
	$fontcnt = 1;
	foreach($fonts_array as $fontname) {
			$fontname = str_replace(" ", "+", $fontname);
			$fontstyle = 'http://fonts.googleapis.com/css?family='.$fontname;
		//	wp_register_style('fontstyle-'.$fontcnt, $fontstyle, '', '');
		//	wp_enqueue_style('fontstyle-'.$fontcnt);
			$fontcnt++;
	}
	 
	 $all_categories = get_categories(array('hide_empty' => 1));
	 $cat_list = array();
	 $cat_options = array();
	 $checked_cats = array();

	foreach ($all_categories as $category) {
    $cat_list[] = "premiumwd_cat_header" . $category->cat_ID;
    $cat_options[] = $category->cat_name;
    $checked_cats[] = "not";
	}
	 
	$all_pages = get_pages();
	$page_options = array();
	$page_list = array();
	$page_list_footer = array();
	$checked_options = array();
	
	foreach ($all_pages as $page){
    $page_list[] = "premiumwd_nav_header_".$page->ID;
    $page_list_footer[] = "premiumwd_nav_footer_".$page->ID;
    $page_title = get_page($page->ID);
    $page_options[] = $page_title->post_title;
    $checked_options[] = "not";
	}

	$options = array(    

	///////////////////////////////////////
	// General Settings Open
	///////////////////////////////////////	
    	array(
        "type" => "section",
        "icon" => "premiumwd-icon-general",
        "title" => "General",
        "id" => "general",
        "expanded" => "true"
		 ),

     	array(
        "section" => "general",
        "type" => "heading",
        "title" => "Main Settings",
        "id" => "general-visual"
   		 ),
     					
		array(
        "under_section" => "general-visual",
        "type" => "select",
        "name" => "Select Width",
        "id" => "premiumwd_width",
        "desc" => "Choose the width of your website",
        "options" => array("960px", "1040px", "1120px"),
		"default" => "960px"),
			
		array(
        "under_section" => "general-visual",
        "type" => "select",
        "name" => "Layout Style",
        "id" => "premiumwd_layout",
        "desc" => "Choose whether you want the layout of this theme to be boxed or wide",
        "options" => array("Float", "Boxed", "Wide"),
        "default" => "Boxed"),
		
    	array(
        "under_section" => "general-visual",
        "type" => "image",
        "placeholder" => "http://example.com/logo.png",
        "name" => "Logo",
        "id" => "premiumwd_logo",
        "desc" => "Paste the URL to your logo, or upload it here. (max: 66x260)",
        "default" => ""),
    
    	array(
        "under_section" => "general-visual",
        "type" => "image",
        "placeholder" => "http://example.com/favicon.png",
        "name" => "Favicon",
        "id" => "premiumwd_favicon",
        "desc" => "Paste the URL to your favicon, or upload it here (resolution of 32x32 or 16x16)",
        "default" => ""),
		   
    	array(
        "under_section" => "general-visual",
        "type" => "text",
        "name" => "Title separator",
        "id" => "premiumwd_title_sep",
        "desc" => "Type a separator to be used in titles (eg. '-' => Home - Page Name )",
        "default" => " |"),
		
		array(
        "under_section" => "general-visual",
        "type" => "checkbox",
        "name" => "Back to Top",
        "id" => array("premiumwd_back_to_top"),        "options" => array(""),
        "desc" => "Display a back to top button for your users.",
        "default" => array("checked")),
		
    	array(
        "section" => "general",
        "type" => "heading",
        "title" => "Code integration",
        "id" => "general-general"
   		),
    
		array(
        "under_section" => "general-general",
        "type" => "checkbox",
        "name" => "Allow these integrations",
        "id" => array("premiumwd_code_allow_google", "premiumwd_code_allow_css", "premiumwd_code_allow_$", "premiumwd_code_allow_childcss"),
        "options" => array("Google analytics", "Custom css", "Custom jQuery", "Child Stylesheet"),
        "desc" => "Choose which code integrations (below) you want to use.",
        "default" => array("checked", "not", "not", "not")),
    	
		array(
        "under_section" => "general-general",
        "type" => "textarea",
        "name" => "Google analytics",
        "display_checkbox_id" => "premiumwd_code_allow_google",
        "placeholder" => "<script>... </script>",
        "id" => "premiumwd_analytics",
        "desc" => "Paste here your google analytics code.",),
    	
		array(
        "under_section" => "general-general",
        "type" => "textarea",
        "name" => "Custom css",
        "display_checkbox_id" => "premiumwd_code_allow_css",
        "placeholder" => "h1 { color: white; }",
        "id" => "premiumwd_custom_css",
        "desc" => "Write here your custom css.",),
    	
		array(
        "under_section" => "general-general",
        "type" => "textarea",
        "display_checkbox_id" => "premiumwd_code_allow_$",
        "name" => "Custom $ Code",
        "placeholder" => "$('h1').hide();",
        "id" => "premiumwd_custom_$",
        "desc" => "This code is executed after document is ready.",),
    	
		array(
        "under_section" => "general-general",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_allow_childcss",
        "name" => "Child stylesheet",
        "id" => "premiumwd_code_childcss",
        "desc" => "Enter the URL of a child stylesheet to display.",
        "placeholder" => "http://www.stylesheet.com/stylesheet.css"),
	
		
	///////////////////////////////////////
	// General Settings Close
	///////////////////////////////////////	
    
	///////////////////////////////////////
	// Page Settings Open
	///////////////////////////////////////	
    	array(
        "type" => "section",
        "icon" => "premiumwd-icon-page-settings",
        "title" => "Page Settings",
        "id" => "layout",
        "expanded" => "false"
    	),
    
	 	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Header",
        "id" => "layout-header",
    	),

		array(
        "under_section" => "layout-header",
        "type" => "checkbox",
        "name" => "Header Scroll",
        "id" => array("premiumwd_allow_scroll"),        "options" => array(""),
        "desc" => "Allow the header to scroll with the page.",
        "default" => array("not")),
	
    	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Blog",
        "id" => "layout-blog"
    	),
    
    	array(
        "under_section" => "layout-blog",
        "type" => "text",
        "name" => "Posts per page",
        "id" => "premiumwd_blog_perpage",
        "desc" => "Type how many posts you want to show per page on blog page template.",
		"default" => "5"),   

		array(
 	   "under_section" => "layout-blog",
        "type" => "checkbox",
		"name" => "Include categories",
        "id" => $cat_list,
        "options" => $cat_options,
        "desc" => "Choose which categories you want to show in the top navigation.",
        "default" => ($checked_cats)),
		
    array(
    "under_section" => "layout-blog", 
    "type" => "small_heading", 
    "display_checkbox_id" => "toggle_checkbox_id",
    "title" => "Post Settings"), 
    
	array(
    "under_section" => "layout-blog", 
    "type" => "checkbox", 
    "name" => "Show share buttons", 
    "id" => array("premiumwd_blog_social_top", "premiumwd_blog_social_bottom"),
    "options" => array("Show at top", "Show at bottom"), 
    "desc" => "Choose whether you want to show share buttons in blog page template.",
    "display_checkbox_id" => "toggle_checkbox_id",
    "default" => array("not", "checked")),  
        
		array(
        "under_section" => "layout-blog",
		"type" => "checkbox_image",
		"show_labels" => "false",
        "name" => "Share buttons",
		"id" => array( "premiumwd_share_twitter", 
            "premiumwd_share_google", 
            "premiumwd_share_fb",
			"premiumwd_share_pinit", 
            "premiumwd_share_digg",
			"premiumwd_share_linkedin" 
			),
        
		"options" => array( "premiumwd_share_twitter", 
            "premiumwd_share_google", 
            "premiumwd_share_fb",
			"premiumwd_share_pinit", 
            "premiumwd_share_digg",
			"premiumwd_share_linkedin" 
			),
        
        "image_src" => array(get_template_directory_uri()."/premiumwd-options/"."assets/share_twitter.png",
            get_template_directory_uri()."/premiumwd-options/"."assets/share_google.png",
            get_template_directory_uri()."/premiumwd-options/"."assets/share_fb.png",
			get_template_directory_uri()."/premiumwd-options/"."assets/share_pinit.png",
            get_template_directory_uri()."/premiumwd-options/"."assets/share_digg.png",
			get_template_directory_uri()."/premiumwd-options/"."assets/share_linkedin.png",),
        
		"desc" => "Choose which share buttons you want to show at bottom of blog posts.",
        "image_size" => array( "96"),
		"default" => array("checked", "checked", "checked", "checked", "checked", "checked"),),
   
 		array(
        "under_section" => "layout-blog",
		"type" => "checkbox",
		"name" => "Author bio",
		"id" => array( "premiumwd_blog_bio" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide author bio in blog page template.",
		"default" => array("checked")),

 		array(
        "under_section" => "layout-blog",
		"type" => "checkbox",
		"name" => "Related posts",
		"id" => array( "premiumwd_blog_related_posts" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide related posts in blog page template.",
		"default" => array("checked")),

   		array(
        "under_section" => "layout-blog",
		"type" => "checkbox",
		"name" => "Comments",
		"id" => array( "premiumwd_blog_comments" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide comments in blog page template.",
		"default" => array("checked")),
	
		array(
        "under_section" => "layout-blog",
		"type" => "checkbox",
		"name" => "Pagnation",
		"id" => array( "premiumwd_blog_pagnation" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide pagnation in blog page template.",
		"default" => array("checked")),
	
    	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Portfolio",
        "id" => "layout-portfolio"
   	 	),
    
   	 	array(
        "under_section" => "layout-portfolio",
        "type" => "text",
        "name" => "Posts per page",
        "id" => "premiumwd_portfolio_perpage",
        "desc" => "Type how many projects you want to show per page on projects page template.",
		"default" => "5"),   
		
		array(
        "under_section" => "layout-portfolio",
        "type" => "text",
        "name" => "Portfolio URL",
        "id" => "premiumwd_portfolio_url",
        "desc" => "Type for portfolio slug for users to be able to switch back and forth when viewing single items.",
		"default" => "portfolio"),   
	
  	 array(
    "under_section" => "layout-portfolio", 
    "type" => "small_heading", 
    "display_checkbox_id" => "toggle_checkbox_id",
    "title" => "Post Settings"), 
    
   		array(
        "under_section" => "layout-portfolio",
		"type" => "checkbox",
		"name" => "Comments",
		"id" => array( "premiumwd_portfolio_comments" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide comments in blog portfolio template.",
		"default" => array("checked")),
    
		array(
        "under_section" => "layout-portfolio",
		"type" => "checkbox",
		"name" => "Related Projects",
		"id" => array( "premiumwd_portfolio_related_projects" ),        "options" => array(""),
        "desc" => "Choose whether you want to show hide related projects in blog portfolio template.",
		"default" => array("checked")),
	
		array(
		"under_section" => "layout-portfolio",
		"type" => "checkbox",
		"name" => "Pagnation",
		"id" => array( "premiumwd_portfolio_pagnation" ),        "options" => array(""),
		"desc" => "Choose whether you want to show hide pagnation in portfolio page template.",
		"default" => array("checked")),
	
    	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Footer",
        "id" => "layout-footer"
    	),
    
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "placeholder" => "",
        "name" => "Copyright",
        "id" => "premiumwd_footer_copyright",
        "desc" => "Paste your copyright here.",
        "default" => ""),
	
   		array(
        "under_section" => "layout-footer",
		"type" => "checkbox",
		"name" => "Widget Area",
		"id" => array( "premiumwd_show_footerwidgets" ),        "options" => array(""),
        "desc" => "Choose whether you want to  widget area.",
		"default" => array("checked")),
	
				array(
			"under_section" => "layout-footer",
			"type" => "checkbox_image",
			"show_labels" => "false",
			"name" => "Social media",
			"id" => array( 
			"premiumwd_social_apple-ping",
            "premiumwd_social_bebo",
            "premiumwd_social_blogger",
			"premiumwd_social_delicious",
			"premiumwd_social_digg",
			"premiumwd_social_dopplr",
			"premiumwd_social_dribble",
			"premiumwd_social_facebook",
			"premiumwd_social_flickr",
			"premiumwd_social_forrst",
			"premiumwd_social_lastfm",
			"premiumwd_social_linkedin",
			"premiumwd_social_mixx",
			"premiumwd_social_myspace",
			"premiumwd_social_netvibes",
			"premiumwd_social_orkut",
			"premiumwd_social_picasa",
			"premiumwd_social_rss",
			"premiumwd_social_sharethis",
			"premiumwd_social_stumbleupon",
			"premiumwd_social_technorati",
			"premiumwd_social_tumblr",
			"premiumwd_social_twitter",
            "premiumwd_social_vimeo",
            "premiumwd_social_yahoo-buzz"
        	),
        
			"options" => array( 
			"premiumwd_social_apple-ping",
            "premiumwd_social_bebo",
            "premiumwd_social_blogger",
			"premiumwd_social_delicious",
			"premiumwd_social_digg",
			"premiumwd_social_dopplr",
			"premiumwd_social_dribble",
			"premiumwd_social_facebook",
			"premiumwd_social_flickr",
			"premiumwd_social_forrst",
			"premiumwd_social_lastfm",
			"premiumwd_social_linkedin",
			"premiumwd_social_mixx",
			"premiumwd_social_myspace",
			"premiumwd_social_netvibes",
			"premiumwd_social_orkut",
			"premiumwd_social_picasa",
			"premiumwd_social_rss",
			"premiumwd_social_sharethis",
			"premiumwd_social_stumbleupon",
			"premiumwd_social_technorati",
			"premiumwd_social_tumblr",
			"premiumwd_social_twitter",
            "premiumwd_social_vimeo",
            "premiumwd_social_yahoo-buzz"
        	),
			
       		"image_src" => array(
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."apple-ping.png",
            get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."bebo.png",
            get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."blogger.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."delicious.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."digg.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."dopplr.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."dribble.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."facebook.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."flickr.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."forrst.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."lastfm.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."linkedin.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."mixx.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."myspace.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."netvibes.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."orkut.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."picasa.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."RSS.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."sharethis.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."stumbleupon.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."technorati.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."tumblr.png",
			get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."twitter.png",
            get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."vimeo.png",
            get_template_directory_uri()."/premiumwd-options/"."assets"."/"."social"."/"."yahoo-buzz.png"
			),

			"image_size" => array("16"),    
			"desc" => "Choose which social icons you want to display in footer.",
			"default" => array("not", "not", "not", 
			"not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not",  
			"not", "not", "not", "not", "not", "not", "not", "not")
			),
   
    
    	array(
        "type" => "small_heading",
        "title" => "Social media links",
        "under_section" => "layout-footer",
    	), 
    	
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Apple Ping",
        "display_checkbox_id" => "premiumwd_social_apple-ping",
        "id" => "premiumwd_social_apple-ping_url",
        "placeholder" => "Apple Ping url",
        "desc" => "Paste url to your Apple Ping (eg.: http://johndoe.deviantart.com/)",),
           
        array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Bebo",
        "display_checkbox_id" => "premiumwd_social_bebo",
        "id" => "premiumwd_social_bebo_url",
        "placeholder" => "Bebo url",
        "desc" => "Paste url to your Bebo (eg.: http://johndoe.deviantart.com/)",),
                           
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Blogger",
        "display_checkbox_id" => "premiumwd_social_blogger",
        "id" => "premiumwd_social_blogger_url",
        "placeholder" => "Blogger url",
        "desc" => "Paste url to your Blogger (eg.: http://johndoe.deviantart.com/)",),    
                
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Delicious",
        "display_checkbox_id" => "premiumwd_social_delicious",
        "id" => "premiumwd_social_delicious_url",
        "placeholder" => "Delicious",
        "desc" => "Paste url to your Delicious (eg.: http://johndoe.deviantart.com/)",),
        	
        array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Digg",
        "display_checkbox_id" => "premiumwd_social_digg",
        "id" => "premiumwd_social_digg_url",
        "placeholder" => "Digg url",
        "desc" => "Paste url to your Digg (eg.: http://johndoe.deviantart.com/)",),
        				
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Dopplr",
        "display_checkbox_id" => "premiumwd_social_dopplr",
        "id" => "premiumwd_social_dopplr_url",
        "placeholder" => "Dobblr url",
        "desc" => "Paste url to your Dopplr (eg.: http://johndoe.deviantart.com/)",),
        	
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Dribble",
        "display_checkbox_id" => "premiumwd_social_dribble",
        "id" => "premiumwd_social_dribble_url",
        "placeholder" => "Dribble url",
        "desc" => "Paste url to your Dribble (eg.: http://johndoe.deviantart.com/)",),
        	
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Facebook",
        "display_checkbox_id" => "premiumwd_social_facebook",
        "id" => "premiumwd_social_facebook_url",
        "placeholder" => "Facebook url",
        "desc" => "Paste url to your Facebook (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Flickr",
        "display_checkbox_id" => "premiumwd_social_flickr",
        "id" => "premiumwd_social_flickr_url",
        "placeholder" => "Flickr url",
        "desc" => "Paste url to your Flickr (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Forrst",
        "display_checkbox_id" => "premiumwd_social_forrst",
        "id" => "premiumwd_social_forrst_url",
        "placeholder" => "Forrst url",
        "desc" => "Paste url to your Forrst (eg.: http://johndoe.deviantart.com/)",),
        						
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Lastfm",
        "display_checkbox_id" => "premiumwd_social_lastfm",
        "id" => "premiumwd_social_lastfm_url",
        "placeholder" => "Lastfm url",
        "desc" => "Paste url to your Lastfm (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Linkedin",
        "display_checkbox_id" => "premiumwd_social_linkedin",
        "id" => "premiumwd_social_linkedin_url",
        "placeholder" => "Linkedin url",
        "desc" => "Paste url to your Linkedin (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Mixx",
        "display_checkbox_id" => "premiumwd_social_mixx",
        "id" => "premiumwd_social_mixx_url",
        "placeholder" => "Mixx url",
        "desc" => "Paste url to your Mixx (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Myspace",
        "display_checkbox_id" => "premiumwd_social_myspace",
        "id" => "premiumwd_social_myspace_url",
        "placeholder" => "Myspace url",
        "desc" => "Paste url to your Myspace (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Netvibes",
        "display_checkbox_id" => "premiumwd_social_netvibes",
        "id" => "premiumwd_social_netvibes_url",
        "placeholder" => "Netvibes url",
        "desc" => "Paste url to your Netvibes (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Orkut",
        "display_checkbox_id" => "premiumwd_social_orkut",
        "id" => "premiumwd_social_orkut_url",
        "placeholder" => "Orkut url",
        "desc" => "Paste url to your Orkut (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Picasa",
        "display_checkbox_id" => "premiumwd_social_picasa",
        "id" => "premiumwd_social_picasa_url",
        "placeholder" => "Picasa url",
        "desc" => "Paste url to your Picasa (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "RSS",
        "display_checkbox_id" => "premiumwd_social_rss",
        "id" => "premiumwd_social_rss_url",
        "placeholder" => "RSS url",
        "desc" => "Paste url to your RSS (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Shareshis",
        "display_checkbox_id" => "premiumwd_social_sharethis",
        "id" => "premiumwd_social_sharethis_url",
        "placeholder" => "Shareshis url",
        "desc" => "Paste url to your Shareshis (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Stumble-Upon",
        "display_checkbox_id" => "premiumwd_social_stumbleupon",
        "id" => "premiumwd_social_stumbleupon_url",
        "placeholder" => "Stumble-Upon url",
        "desc" => "Paste url to your Stumble-Upon (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Technorati",
        "display_checkbox_id" => "premiumwd_social_technorati",
        "id" => "premiumwd_social_technorati_url",
        "placeholder" => "Technorati url",
        "desc" => "Paste url to your Technorati (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Tumblr",
        "display_checkbox_id" => "premiumwd_social_tumblr",
        "id" => "premiumwd_social_tumblr_url",
        "placeholder" => "Tumblr url",
        "desc" => "Paste url to your Tumblr (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Twitter",
        "display_checkbox_id" => "premiumwd_social_twitter",
        "id" => "premiumwd_social_twitter_url",
        "placeholder" => "Twitter",
        "desc" => "Paste url to your Twitter (eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Vimeo",
        "display_checkbox_id" => "premiumwd_social_vimeo",
        "id" => "premiumwd_social_vimeo_url",
        "placeholder" => "Vimeo url",
        "desc" => "Paste url to your Vimeo(eg.: http://johndoe.deviantart.com/)",),
        			
		array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Yahoo Buzz",
        "display_checkbox_id" =>  "premiumwd_social_yahoo-buzz",
        "id" => "premiumwd_social_yahoo-buzz_url",
        "placeholder" => "Yahoo Buzz",
        "desc" => "Paste url to your Yahoo Buzz (eg.: http://johndoe.deviantart.com/)",),
        
	
	    array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Contact",
        "id" => "layout-contact"
    	),
				
    	array(
        "under_section" => "layout-contact",
		"type" => "checkbox",
		"name" => "Contact Form",
		"id" => array( "premiumwd_contact_show" ),        "options" => array(""), //Required
        "desc" => "Choose whether you want to show contact form in contact page template.",
		"default" => array("not")),
    
   		array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "Your e-mail",
        "display_checkbox_id" => "premiumwd_contact_show",
        "default" => get_option('admin_email'),
        "id" => "premiumwd_contact_mail",
        "desc" => "Enter your e-mail, for use in the contact form",),
    
    	array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "E-mail subject",
        "display_checkbox_id" => "premiumwd_contact_show",
        "default" => "Innovate Theme - Email",
        "id" => "premiumwd_contact_subject",
        "desc" => "Write a subject for received e-mails.",),
    
    	array(
        "under_section" => "layout-contact",
        "type" => "textarea",
        "display_checkbox_id" => "premiumwd_contact_show",
        "name" => "E-mail message",
        "default" => "Your message was sent successfully",
        "id" => "premiumwd_contact_message",
        "desc" => "Write a message that will be shown when user sends an e-mail.",),
			
	
		
	///////////////////////////////////////
	// Page Settings Close
	///////////////////////////////////////	
    
	///////////////////////////////////////
	// Slider Settings Open
	///////////////////////////////////////	
    	array(
        "type" => "section",
        "icon" => "premiumwd-icon-slider-settings",
        "title" => "Slider Settings",
        "id" => "slider",
        "expanded" => "false"
    	),
    
    	array(
        "section" => "slider",
        "type" => "heading",
        "title" => "Slider",
        "id" => "slider-settings"
    	),    
		
		array(
        "under_section" => "slider-settings",
        "type" => "checkbox",
        "name" => "Activate Slider",
        "id" => array("premiumwd_code_revolution_slider","premiumwd_code_nivo_slider"),
        "options" => array("Revolution Slider","Nivo Slider"),
        "desc" => "Choose which slider you want to use.",
        "default" => array("not","not")),

		
		///////////////////////////////////////
		// Nivo Slider
		///////////////////////////////////////	
		
	    array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 1",
        "id" => "premiumwd_nivo_slider_image1",
        "default" => ""),
		
		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 1",
        "id" => "premiumwd_orbit_link1",
        "default" => "#"),
		
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 2",
        "id" => "premiumwd_nivo_slider_image2",
        "default" => ""),
		
		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 2",
        "id" => "premiumwd_orbit_link2",
        "default" => "#"),
		
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 3",
        "id" => "premiumwd_nivo_slider_image3",
        "default" => ""),
		
		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 3",
        "id" => "premiumwd_orbit_link3",
        "default" => "#"),
		
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 4",
        "id" => "premiumwd_nivo_slider_image4",
        "default" => ""),
		
		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 4",
        "id" => "premiumwd_orbit_link4",
        "default" => "#"),		
		
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 5",
        "id" => "premiumwd_nivo_slider_image5",
        "default" => ""),

		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 5",
        "id" => "premiumwd_orbit_link5",
        "default" => "#"),
				
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 6",
        "id" => "premiumwd_nivo_slider_image6",
        "default" => ""),

		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 6",
        "id" => "premiumwd_orbit_link6",
        "default" => "#"),
				
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 7",
        "id" => "premiumwd_nivo_slider_image7",
        "default" => ""),

		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 7",
        "id" => "premiumwd_orbit_link7",
        "default" => "#"),
				
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "image",
        "placeholder" => "http://example.com/headerbg.png",
        "name" => "Custom Image 8",
        "id" => "premiumwd_nivo_slider_image8",
        "default" => ""),

		array(
        "under_section" => "slider-settings",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_nivo_slider",
        "name" => "Link 8",
        "id" => "premiumwd_orbit_link8",
        "default" => "#"),
		   
    	array(     
		"display_checkbox_id" => "premiumwd_code_nivo_slider",   
        "under_section" => "slider-settings",
		"type" => "select",
		"name" => "Animation Effect",
		"id" => "premiumwd_animation_effect",
		"options" => array( "random", "fold", "fade", "slide down", "slide down left", "slice up", "slice up down", "slice up left", "slice up down left"),					
		"desc" => "Choose one of these transition animations.",
		"default" => "random" ),  
    
        array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "text",
        "name" => "Number of Slices",
        "default" => "15",
        "id" => "premiumwd_slider_slices"),
    
        array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "text",
        "name" => "Animation Speed",
        "default" => "500",
        "id" => "premiumwd_slider_animation_speed"),
 
        array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "text",
        "name" => "Pause Interval",
        "default" => "10000",
        "id" => "premiumwd_slider_pause_interval"),

		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "checkbox",
        "name" => "Pause on Hover",
        "id" => array("premiumwd_slider_pause_hover_show"),        "options" => array(""),
        "desc" => "Pause when mouse is hovering on images.",
        "default" => array("true")),
		
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "checkbox",
        "name" => "Navigation Menu",
        "id" => array("premiumwd_slider_navigation_show"),        "options" => array(""),
        "desc" => "Show navigation menu.",
        "default" => array("true")),
    
		array(
		"display_checkbox_id" => "premiumwd_code_nivo_slider",
        "under_section" => "slider-settings",
        "type" => "checkbox",
        "name" => "Navigation Arrows",
        "id" => array("premiumwd_slider_direction_show"),        "options" => array(""),
        "desc" => "Show directional navigation arrows.",
        "default" => array("true")),
		
		

	///////////////////////////////////////
	// Slider Settigs Close
	///////////////////////////////////////	
	
 
 	///////////////////////////////////////
	// Style Settings Open
	///////////////////////////////////////	
	    array(
        "type" => "section",
        "icon" => "premiumwd-icon-style-settings",
        "title" => "Style Settings",
        "id" => "style",
        "expanded" => "false"
    	),
	
   		array(
        "section" => "style",
        "type" => "heading",
        "title" => "Typography",
        "id" => "style-typography"
   		 ),
    	
		array(
		"under_section" => "style-typography", 
		"type" => "small_heading", 
		"title" => "Header"), 
		
 	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Logo", 
		"id" => "logo_fontsize", 
		"options" => array('26px','28px', '30px', '32px', '34px', '36px', '38px', '40px'),
		"desc" => "",
		"default" => "26px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "logo_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Header Menu", 
		"id" => "header_menu_fontsize", 
		"options" => array('12px','14px', '16px', '18px', '20px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "header_menu_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),   
		
		array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Sub Menu", 
		"id" => "sub_menu_fontsize", 
		"options" => array('12px','13px','14px', '15px', '16px'),
		"desc" => "",
		"default" => "13px"),
		
		array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "sub_menu_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),  
	
    array(
    "under_section" => "style-typography", 
    "type" => "small_heading", 
    "title" => "Body"), 
	    
 	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Header Title", 
		"id" => "header_title_fontsize", 
		"options" => array('20px', '22px', '24px', '26px', '28px', '30px'),
		"desc" => "",
		"default" => "20px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "header_title_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "header_title_fontcolor", 
		"default" => "333333"),
		
 	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Sidebar Title", 
		"id" => "sidebar_title_fontsize", 
		"options" => array('12px', '14px', '16px', '18px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "sidebar_title_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "sidebar_title_fontcolor", 
		"default" => "333333"),

 	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Related Posts", 
		"id" => "related_posts_fontsize", 
		"options" => array('12px', '14px', '16px', '18px'),
		"desc" => "",
		"default" => "14px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "related_posts_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "related_posts_fontcolor", 
		"default" => "333333"),
	
 	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Pagination", 
		"id" => "pagination_fontsize", 
		"options" => array( '10px', '12px', '14px', '16px', '18px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "pagination_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		   

	array(
    "under_section" => "style-typography", 
    "type" => "small_heading", 
    "title" => "Footer"), 
	    
  	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Footer Title", 
		"id" => "footer_title_fontsize", 
		"options" => array('12px', '14px', '16px', '18px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "footer_title_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "footer_title_fontcolor", 
		"default" => "333333"),
	
  	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Footer Content", 
		"id" => "footer_content_fontsize", 
		"options" => array('12px', '14px', '16px', '18px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "footer_content_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "footer_content_fontcolor", 
		"default" => "333333"),
			
  	    array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Copyright", 
		"id" => "copyright_fontsize", 
		"options" => array( '10px', '12px', '14px', '16px', '18px', '20px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "copyright_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		    
   		array(
        "under_section" => "style-typography", 
		"type" => "color", 
		"name" => "", 
		"id" => "copyright_fontcolor", 
		"default" => "333333"),

		array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "Footer Menu", 
		"id" => "footer_menu_fontsize", 
		"options" => array( '10px', '12px', '14px', '16px', '18px', '20px'),
		"desc" => "",
		"default" => "12px"),
 
        array(
        "under_section" => "style-typography", 
		"type" => "select", 
		"name" => "", 
		"id" => "footer_menu_fontfamily", 
		"options" => $fonts_array,
		"desc" => "",
		"default" => ""),
		  

        array(
        "under_section" => "style-typography", 
		"type" => "small_heading", 
		"name" => "blankline", 
		"id" => "style_blank_line", 
		"default" => "333333"),
        		
   array(
   "section" => "style",
   "type" => "heading",
   "title" => "Backgrounds",
   "id" => "style-backgrounds"
    ),
	
	array(
    "under_section" => "style-backgrounds",
    "type" => "checkbox",
    "name" => "Custom background style.",
    "id" => array("premiumwd_allow_custom_background", "premiumwd_allow_custom_color"),
    "options" => array("Custom Background Image", "Custom Background Color"),
    "desc" => "Choose which type of background style you want.",
    "default" => array("true", "not")),
		
   	array(
    "under_section" => "style-backgrounds", 
    "type" => "image", 
	"placeholder" => "http://example.com/background_image.png",
    "name" => "Custom background image.", 
	"display_checkbox_id" => "premiumwd_allow_custom_background",
    "id" => "premiumwd_custom_background", 
	"desc" => "You can upload your own background for your theme.",
    "default" => ""
	),
	 
	array(
    "under_section" => "style-backgrounds", 
	"type" => "color", 
	"name" => "Custom background color.", 
	"id" => "premiumwd_custom_color",
	"display_checkbox_id" => "premiumwd_allow_custom_color", 
	"default" => "fefefe"),

	array(
    "under_section" => "style-backgrounds",
    "type" => "checkbox",
    "name" => "Stock background styles.",
    "id" => array("premiumwd_allow_stock_patterns"),
    "options" => array("Stock Background Patterns"),
    "desc" => "Choose which type of background style you want.",
    "default" => array("checked")),
	
	 array(
    "under_section" => "style-backgrounds", 
	"display_checkbox_id" => "premiumwd_allow_stock_patterns",
    "type" => "small_heading",
    "title" => "Stock Background Patterns"), 
	
	array(
    "under_section" => "style-backgrounds", 
	"display_checkbox_id" => "premiumwd_allow_stock_patterns",
	"type" => "checkbox_image",
	"show_labels" => "false",
    "name" => "Background Patterns",
	"id" => array( 
		   "premiumwd_stock_pattern0", 
           "premiumwd_stock_pattern1",
		   "premiumwd_stock_pattern2",
		   "premiumwd_stock_pattern3",
		   "premiumwd_stock_pattern4",
		   "premiumwd_stock_pattern5",
		   "premiumwd_stock_pattern6",
		   "premiumwd_stock_pattern7",
		   "premiumwd_stock_pattern8",
		   "premiumwd_stock_pattern9",
		   "premiumwd_stock_pattern10",
		   "premiumwd_stock_pattern11",
		   "premiumwd_stock_pattern12",
		   "premiumwd_stock_pattern13",
		   "premiumwd_stock_pattern14",
		   "premiumwd_stock_pattern15",
		   "premiumwd_stock_pattern16",
		   "premiumwd_stock_pattern17",
		   "premiumwd_stock_pattern18",
		   "premiumwd_stock_pattern19",
		   "premiumwd_stock_pattern20",
		   "premiumwd_stock_pattern21",
		   "premiumwd_stock_pattern22",
		   "premiumwd_stock_pattern23",
		   "premiumwd_stock_pattern24",
		   "premiumwd_stock_pattern25",
		   "premiumwd_stock_pattern26",
		   "premiumwd_stock_pattern27",
		   "premiumwd_stock_pattern28",
		   "premiumwd_stock_pattern29",
		   "premiumwd_stock_pattern30",
		   "premiumwd_stock_pattern31",
		   "premiumwd_stock_pattern32",
		   "premiumwd_stock_pattern33",
		   "premiumwd_stock_pattern34",
		   "premiumwd_stock_pattern35",
		   "premiumwd_stock_pattern36",
		   "premiumwd_stock_pattern37",
		   "premiumwd_stock_pattern38",
		   "premiumwd_stock_pattern39",
		   "premiumwd_stock_pattern40",
		   "premiumwd_stock_pattern41",
		   "premiumwd_stock_pattern42",
		   "premiumwd_stock_pattern43",
		   "premiumwd_stock_pattern44",
		   "premiumwd_stock_pattern45",
		   "premiumwd_stock_pattern46", 
		   "premiumwd_stock_pattern47",
		   "premiumwd_stock_pattern48",
		   "premiumwd_stock_pattern49",
		   "premiumwd_stock_pattern50",
		   "premiumwd_stock_pattern51",
		   "premiumwd_stock_pattern52",
		   "premiumwd_stock_pattern53",
		   "premiumwd_stock_pattern54",
		   "premiumwd_stock_pattern55",
		   "premiumwd_stock_pattern56",
		   "premiumwd_stock_pattern57",
		   "premiumwd_stock_pattern58",
		   "premiumwd_stock_pattern59",
		   "premiumwd_stock_pattern60",
		   "premiumwd_stock_pattern61",
		   "premiumwd_stock_pattern62",
		   "premiumwd_stock_pattern63",
		   "premiumwd_stock_pattern64",
		   "premiumwd_stock_pattern65",
		   "premiumwd_stock_pattern66",
		   "premiumwd_stock_pattern67",
		   "premiumwd_stock_pattern68"
			),
        
	"options" => array( 
			"Pattern 0",
			"Pattern 1",
			"Pattern 2",
			"Pattern 3",
			"Pattern 4",
			"Pattern 5",
			"Pattern 6",
			"Pattern 7",
			"Pattern 8",
			"Pattern 9",
			"Pattern 10", 
			"Pattern 11",
			"Pattern 12",
			"Pattern 13",
			"Pattern 14",
			"Pattern 15",
			"Pattern 16",
			"Pattern 17",
			"Pattern 18",
			"Pattern 19",
			"Pattern 20", 
			"Pattern 21",
			"Pattern 22",
			"Pattern 23",
			"Pattern 24",
			"Pattern 25",
			"Pattern 26",
			"Pattern 27",
			"Pattern 28",
			"Pattern 29",
			"Pattern 30", 
			"Pattern 31",
			"Pattern 32",
			"Pattern 33",
			"Pattern 34",
			"Pattern 35",
			"Pattern 36",
			"Pattern 37",
			"Pattern 38",
			"Pattern 39",
			"Pattern 40", 
			"Pattern 41",
			"Pattern 42",
			"Pattern 43",
			"Pattern 44",
			"Pattern 45",
			"Pattern 46",
			"Pattern 47",
			"Pattern 48",
			"Pattern 49",
			"Pattern 50", 
			"Pattern 51",
			"Pattern 52",
			"Pattern 53",
			"Pattern 54",
			"Pattern 55",
			"Pattern 56",
			"Pattern 57",
			"Pattern 58",
			"Pattern 59",
			"Pattern 60", 
			"Pattern 61",
			"Pattern 62",
			"Pattern 63",
			"Pattern 64",
			"Pattern 65",
			"Pattern 66",
			"Pattern 67",
			"Pattern 68"
			),
        
    "image_src" => array(
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-0.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-1.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-2.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-3.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-4.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-5.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-6.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-7.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-8.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-9.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-10.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-11.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-12.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-13.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-14.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-15.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-16.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-17.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-18.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-19.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-20.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-21.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-22.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-23.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-24.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-25.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-26.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-27.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-28.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-29.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-30.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-31.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-32.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-33.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-34.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-35.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-36.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-37.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-38.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-39.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-40.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-41.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-42.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-43.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-44.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-45.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-46.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-47.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-48.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-49.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-50.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-51.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-52.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-53.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-54.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-55.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-56.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-57.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-58.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-59.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-60.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-61.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-62.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-63.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-64.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-65.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-66.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-67.jpg",
			get_template_directory_uri()."/premiumwd-options/"."assets/"."patterns/pattern-68.jpg"
			),
        
	"desc" => "Choose a stock background pattern can also select a custom color from activing it above.",
    "image_size" => array("25"),
	"default" => array(
	"not", "not", "not", "not", "not", "not", "not", "not", "not","not", 
	"not", "not", "not", "not", "checked", "not", "not", "not", "not","not",
	"not", "not", "not", "not", "not", "not", "not", "not", "not","not",
	"not", "not", "not", "not", "not", "not", "not", "not", "not","not",
	"not", "not", "not", "not", "not", "not", "not", "not", "not","not",
	"not", "not", "not", "not", "not", "not", "not", "not", "not","not",
	"not", "not", "not", "not", "not", "not","not", "not" )
	),
	

	 array(
    "under_section" => "style-backgrounds",
    "type" => "small_heading",
    "title" => "Predefined Color Palletes"), 
	
	array(
    "under_section" => "style-backgrounds",
	"type" => "checkbox_image",
	"show_labels" => "false",
    "name" => "Color skins",
	"id" => array( 
			"premiumwd_default_skin_grey", 
            "premiumwd_default_skin_black", 
            "premiumwd_default_skin_white",
			"premiumwd_default_skin_yellow", 
            "premiumwd_default_skin_purple",
			"premiumwd_default_skin_orange",
			"premiumwd_default_skin_red",
			"premiumwd_default_skin_blue",
			"premiumwd_default_skin_green",    
			),
        
	"options" => array( 
			"Modern Grey", 
            "Dark Black", 
            "Light White",
			"Butter Yellow", 
            "Plum Purple",
			"Tangerine Orange",
			"Strawberry Red",
			"Sky Blue",
			"Chameleon Green",    
			),
        
    "image_src" => array(
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/grey.png",
            get_template_directory_uri()."/premiumwd-options/"."skins/"."images/black.png",
            get_template_directory_uri()."/premiumwd-options/"."skins/"."images/white.png",
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/yellow.png",
            get_template_directory_uri()."/premiumwd-options/"."skins/"."images/purple.png",
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/orange.png",
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/red.png",
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/blue.png",
			get_template_directory_uri()."/premiumwd-options/"."skins/"."images/green.png",
			),
        
	"desc" => "Choose one default color skin.",
    "image_size" => array("96"),
	"default" => array("not", "not", "not", "not", "not", "not", "not", "not", "not")
	),
	
	 array(
    "under_section" => "style-backgrounds",
    "type" => "small_heading",
    "title" => "Custom Colors"), 
	
	
	 array(
    "under_section" => "style-backgrounds",
    "type" => "small_heading", 
    "title" => "Header"), 
	
 	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Header background color", 
    "id" => "header_background_color", 
    "default" => "ffffff"
	),
      
	
    array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Drop down background color", 
    "id" => "drop_down_background_color", 
    "default" => "ffffff"
	),
	  
     array(
    "under_section" => "style-backgrounds",
    "type" => "small_heading", 
    "title" => "Body"), 

	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Slider background color", 
    "id" => "slider_background_color", 
    "default" => "ffffff"
	),	

	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Body background color", 
    "id" => "body_background_color", 
    "default" => "ffffff"
	),	
	
	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Lines & borders color", 
    "id" => "lines_border_color", 
    "default" => "ededed"
	),	
		
    array(
    "under_section" => "style-backgrounds",
    "type" => "small_heading", 
    "title" => "Footer"), 
	
	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Footer background color", 
    "id" => "footer_background_color", 
    "default" => "333333"
	),
	
	array(
    "under_section" => "style-backgrounds",
    "type" => "color", 
    "name" => "Widget Background Color", 
    "id" => "widget_background_color", 
    "default" => "444444"
	),
	
	array(
    "section" => "style",
    "type" => "heading",
    "title" => "Text Styles",
    "id" => "style-text"
    ),
    
    array(
    "under_section" => "style-text", 
    "type" => "small_heading", 
    "title" => "Header"), 
	
    array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Header menu active color", 
    "id" => "header_menu_active_color", 
    "default" => "333333"
	),

	 array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Header menu link color", 
    "id" => "header_menu_link_color", 
    "default" => "999999"
	),

    array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Header menu hover color", 
    "id" => "header_menu_hover_color", 
    "default" => "666666"
	),

    array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Sub header menu link color", 
    "id" => "sub_header_menu_link_color", 
    "default" => "999999"
	),

    array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Sub header menu hover", 
    "id" => "sub_header_menu_hover", 
    "default" => "666666"
	),
	
	
	array(
    "under_section" => "style-text", 
    "type" => "small_heading", 
    "title" => "Body"), 
	
	array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Main body text color", 
    "id" => "main_body_text_color", 
    "default" => "454545"
	),
	
	array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Main links color", 
    "id" => "main_links_color", 
    "default" => "222222"
	),
	
	array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Main links hover color", 
    "id" => "main_links_hover_color", 
    "default" => "01B9F7"
	),

	array(
    "under_section" => "style-text", 
    "type" => "small_heading", 
    "title" => "Footer"), 
	
	array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Footer links color", 
    "id" => "footer_links_color", 
    "default" => "D6D6D6"
	),
	
	array(
    "under_section" => "style-text", 
    "type" => "color", 
    "name" => "Footer links hover color", 
    "id" => "footer_links_hover", 
    "default" => "01B9F7"
	),		
	///////////////////////////////////////
	// Style Settings Close
	///////////////////////////////////////	
 	 
	///////////////////////////////////////
	// Translation Open
	///////////////////////////////////////	
	    array(
        "type" => "section",
        "icon" => "premiumwd-icon-translation",
        "title" => "Translation",
        "id" => "translation",
        "expanded" => "false"
    	),
        
   		array(
        "section" => "translation",
        "type" => "heading",
        "title" => "Comments",
        "id" => "translation-comments"),
		
        array(
        "under_section" => "translation-comments",
        "type" => "text",
        "name" => "Leave a Comment Text",
        "default" => "Leave a Comment",
		"desc" => "Text for Leave a Comment after article",
        "id" => "premiumwd_translation_comments_leave_comment"), 
		
        array(
        "under_section" => "translation-comments",
        "type" => "text",
        "name" => "Name Text",
        "default" => "Name",
		"desc" => "Name shown in the comment form",
        "id" => "premiumwd_translation_comments_name"), 

        array(
        "under_section" => "translation-comments",
        "type" => "text",
        "name" => "Email Text",
        "default" => "Email",
		"desc" => "Email shown in the comment form",
        "id" => "premiumwd_translation_comments_email"), 

        array(
        "under_section" => "translation-comments",
        "type" => "text",
        "name" => "Website Text",
        "default" => "Website",
		"desc" => "Website shown in the comment form",
        "id" => "premiumwd_translation_comments_website"
		), 
		
			
		array(
        "section" => "translation",
        "type" => "heading",
        "title" => "Portfolio",
        "id" => "translation-portfolio"),
        
        array(
        "under_section" => "translation-portfolio",
        "type" => "text",
        "name" => "By Text",
        "default" => "By",
		"desc" => "By Author",
        "id" => "premiumwd_translation_portfolio_by"), 

        array(
        "under_section" => "translation-portfolio",
        "type" => "text",
        "name" => "Posted On Text",
        "default" => "Posted on",
		"desc" => "Posted on Date",
        "id" => "premiumwd_translation_portfolio_posted"),     

   		array(
        "section" => "translation",
        "type" => "heading",
        "title" => "Search",
        "id" => "translation-search"
    	),
    
        array(
        "under_section" => "translation-search",
        "type" => "text",
        "name" => "Search Results Text",
        "default" => "Search results for",
		"desc" => "Enter Search page results text",
        "id" => "premiumwd_translation_search_results"),    
    
        array(
        "under_section" => "translation-search",
        "type" => "textarea",
        "name" => "No Results Text",
        "default" => "No results found. Please try a different keyword",
		"desc" => "Enter a message to display on your results not found.",
        "id" => "premiumwd_translation_search_none"),    
	
	    array(
        "section" => "translation",
        "type" => "heading",
        "title" => "404",
        "id" => "translation-404"
    	),
    
    	array(
        "under_section" => "translation-404",
        "type" => "image",
        "placeholder" => "http://example.com/404_error_image.png",
        "name" => "404 featured image",
        "id" => "premiumwd_404_image",
        "desc" => "Make sure Image is not larger than width 920.",
        "default" => ""),    

   		array(
        "under_section" => "translation-404",
        "type" => "text",
        "default" => "404 page",
        "name" => "404 page title",
        "id" => "premiumwd_404_title",
        "desc" => "Enter 404 page title."),
    
    	array(
        "under_section" => "translation-404",
        "type" => "textarea",
        "name" => "404 error message",
        "default" => "<p>Oops... Something went wrong.</p>",
        "id" => "premiumwd_404",
        "desc" => "Enter a message to display on your 404 (page not found) error pages."),
	///////////////////////////////////////
	// Translation Close
	///////////////////////////////////////	
	

);
?>
