<?php
/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2012 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/
?>
        <ul class="post-social-section">
        <li>Share This:</li>
        <?php if (get_option('premiumwd_share_google-plus', 'true') == 'true') : ?><li><a class="fa fa-google-plus" href="https://plus.google.com/share?url=<?php the_permalink(); ?>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a></li><?php endif; ?>
        <?php if (get_option('premiumwd_share_facebook', 'true') == 'true') : ?><li><a href="http://www.facebook.com/share.php?u=<?php the_permalink(); ?>&title=[TITLE]" class="fa fa-facebook" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a></li><?php endif; ?>
        <?php if (get_option('premiumwd_share_linkedin', 'true') == 'true') : ?><li><a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php the_permalink(); ?>&title=<?php the_title(); ?>&source=<?php get_site_url(); ?>" class="fa fa-linkedin" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a></li><?php endif; ?>
        <?php if (get_option('premiumwd_share_pinterest', 'true') == 'true') : ?><li><a href="http://pinterest.com/pin/create/button/?url=<?php the_permalink(); ?>" class="fa fa-pinterest" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a></li><?php endif; ?>
        <?php if (get_option('premiumwd_share_twitter', 'true') == 'true') : ?><li><a href="http://twitter.com/home?status=<?php the_title(); ?>+<?php the_permalink(); ?>" class="fa fa-twitter" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a></li><?php endif; ?>
        </ul>