<?php 
/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2012 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/
?>
						<ul class="socials">
                        <?php if (get_option('premiumwd_social_twitter', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_twitter_url')); ?>"><i class="fa fa-twitter"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_facebook', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_facebook_url')); ?>"><i class="fa fa-facebook"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_linkedin', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_linkedin_url')); ?>"><i class="fa fa-linkedin"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_google-plus', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_google-plus_url')); ?>"><i class="fa fa-google-plus"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_dribbble', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_dribbble_url')); ?>"><i class="fa fa-dribbble"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_youtube', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_youtube_url')); ?>"><i class="fa fa-youtube"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_rss', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_rss_url')); ?>"><i class="fa fa-rss"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_pinterest', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_pinterest_url')); ?>"><i class="fa fa-pinterest"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_skype', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_skype_url')); ?>"><i class="fa fa-skype"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_instagram', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_instagram_url')); ?>"><i class="fa fa-instagram"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_flickr', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_flickr_url')); ?>"><i class="fa fa-flickr"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_tumblr', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_tumblr_url')); ?>"><i class="fa fa-tumblr"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_dropbox', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_dropbox_url')); ?>"><i class="fa fa-dropbox"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_foursquare', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_foursquare_url')); ?>"><i class="fa fa-foursquare"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_stackexchange', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_stackexchange_url')); ?>"><i class="fa fa-stackexchange"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_weibo', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_weibo_url')); ?>"><i class="fa fa-weibo"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_github', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_github_url')); ?>"><i class="fa fa-github"></i></a></li><?php endif; ?>
                        <?php if (get_option('premiumwd_social_envelope', 'false') == 'true'): ?><li><a href="<?php echo stripslashes (get_option('premiumwd_social_envelope_url')); ?>"><i class="fa fa-envelope"></i></a></li><?php endif; ?>
                        </ul>
                       

		