<?php

/***************************************************************************/
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*  			Built by Chris Rodriguez. http://premiumwd.com
/*  				Copyright (C) 2012 Premiumwd
/*
/***************************************************************************/
/***************************************************************************/

	global $fontArrays;	 
	
	$all_pages = get_pages();
	$page_options = array();
	$page_list = array();
	$page_list_footer = array();
	$checked_options = array();
	
	foreach ($all_pages as $page){
    $page_list[] = "premiumwd_nav_header_".$page->ID;
    $page_list_footer[] = "premiumwd_nav_footer_".$page->ID;
    $page_title = get_page($page->ID);
    $page_options[] = $page_title->post_title;
    $checked_options[] = "not";
	}

	$options = array(    

	///////////////////////////////////////
	// General Settings Open
	///////////////////////////////////////	
    	array(
        "type" => "section",
        "icon" => "fa fa-cog",
        "title" => "General",
        "id" => "general",
        "expanded" => "true"
	),

     	array(
        "section" => "general",
        "type" => "heading",
        "title" => "Main Settings",
        "id" => "general-visual"
   	),

    	array(
        "under_section" => "general-visual",
        "type" => "image",
        "placeholder" => "http://example.com/logo.png",
        "name" => "Logo",
        "id" => "premiumwd_logo",
        "desc" => "Paste the URL to your logo, or upload it here.",
        "default" => ""
        ),
    
    	array(
        "under_section" => "general-visual",
        "type" => "image",
        "placeholder" => "http://example.com/favicon.png",
        "name" => "Favicon",
        "id" => "premiumwd_favicon",
        "desc" => "Paste the URL to your favicon, or upload it here (resolution of 32x32 or 16x16)",
        "default" => ""
        ),
		   
    	array(
        "under_section" => "general-visual",
        "type" => "text",
        "name" => "Title separator",
        "id" => "premiumwd_title_sep",
        "desc" => "Type a separator to be used in titles (eg. '-' => Home - Page Name )",
        "default" => " |"
        ),		

	array(
        "under_section" => "general-visual",
        "type" => "checkbox",
        "name" => "Load Screen",
        "id" => array("premiumwd_loader"),
	"options" => array("Yes"),
        "desc" => "Add a loading icon before page is loaded.",
        "default" => array("checked")
        ),

	array(
        "under_section" => "general-visual",
        "type" => "checkbox",
        "name" => "Responsive",
        "id" => array("premiumwd_responsive"),
	"options" => array("Yes"),
        "desc" => "Make your website responsive to different devices.",
        "default" => array("checked")
        ),


	array(
        "under_section" => "general-visual",
        "type" => "text",
        "placeholder" => "",
        "name" => "Copyright",
        "id" => "premiumwd_copyright",
        "desc" => "Paste your copyright here.",
        "default" => ""),
 
    	array(
        "section" => "general",
        "type" => "heading",
        "title" => "Code integration",
        "id" => "general-general"
   	),
    
	array(
        "under_section" => "general-general",
        "type" => "checkbox",
        "name" => "Allow these integrations",
        "id" => array("premiumwd_code_allow_google", "premiumwd_code_allow_css", "premiumwd_code_allow_$", "premiumwd_code_allow_childcss"),
        "options" => array("Google analytics", "Custom css", "Custom jQuery", "Child Stylesheet"),
        "desc" => "Choose which code integrations (below) you want to use.",
        "default" => array("checked", "not", "not", "not")
        ),
    	
	array(
        "under_section" => "general-general",
        "type" => "textarea",
        "name" => "Google analytics",
        "display_checkbox_id" => "premiumwd_code_allow_google",
        "placeholder" => "<script>... </script>",
        "id" => "premiumwd_analytics",
        "desc" => "Paste here your google analytics code."
        ),
    	
	array(
        "under_section" => "general-general",
        "type" => "textarea",
        "name" => "Custom css",
        "display_checkbox_id" => "premiumwd_code_allow_css",
        "placeholder" => "h1 { color: white; }",
        "id" => "premiumwd_custom_css",
        "desc" => "Write here your custom css."
        ),
    	
	array(
        "under_section" => "general-general",
        "type" => "textarea",
        "display_checkbox_id" => "premiumwd_code_allow_$",
        "name" => "Custom $ Code",
        "placeholder" => "$('h1').hide();",
        "id" => "premiumwd_custom_$",
        "desc" => "This code is executed after document is ready."
        ),
    	
	array(
        "under_section" => "general-general",
        "type" => "text",
        "display_checkbox_id" => "premiumwd_code_allow_childcss",
        "name" => "Child stylesheet",
        "id" => "premiumwd_code_childcss",
        "desc" => "Enter the URL of a child stylesheet to display.",
        "placeholder" => "http://www.stylesheet.com/stylesheet.css"
        ),
	
		
	array(
        "section" => "general",
        "type" => "heading",
        "title" => "Performance",
        "id" => "general-performance"
   	),

	array(
        "under_section" => "general-performance",
        "type" => "checkbox",
        "name" => "Minify HTML",
        "id" => array("premiumwd_minify_html"),        
        "options" => array("Yes"),
        "desc" => "Increase the performance of your website page load by minifying the size of your HTML.",
        "default" => array("checked")
        ),
		
	array(
        "under_section" => "general-performance",
        "type" => "checkbox",
        "name" => "Defer Js parsing",
        "id" => array("premiumwd_defer_js"),        
        "options" => array("Yes"),
        "desc" => "Allow your JS files to load after page load to reduce the initial load time. (Highly Recommended)",
        "default" => array("checked")
        ),

	array(
        "under_section" => "general-performance",
        "type" => "checkbox",
        "name" => "Remove query strings from static resources",
        "id" => array("premiumwd_query_strings"),        
        "options" => array("Yes"),
        "desc" => "Help caching and speed performance by removing query strings. (Highly Recommended)",
        "default" => array("checked")
        ),

	array(
        "under_section" => "general-performance",
        "type" => "checkbox",
        "name" => "Add lazyload for images",
        "id" => array("premiumwd_lazy_load"),        
        "options" => array("Yes"),
        "desc" => "Help speed performance allowing images to load when not in screen view. (Highly Recommended)",
        "default" => array("checked")
        ),
		
		
	///////////////////////////////////////
	// General Settings Close
	///////////////////////////////////////	
    
	///////////////////////////////////////
	// Page Settings Open
	///////////////////////////////////////	
    	array(
        "type" => "section",
        "icon" => "fa fa-copy",
        "title" => "Page Settings",
        "id" => "layout",
        "expanded" => "false"
    	),
					
    	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Portfolio",
        "id" => "layout-portfolio"
   	 ),
	
	array(
        "under_section" => "layout-portfolio",
        "type" => "checkbox",
	"default" => array("checked"),		
	"name" => "Portfolio Filter",
 	"options" => array("Yes"), //Required
	"id" => array("premiumwd_filter"),
        "desc" => "Choose whether you want to show a filter."
        ),

	array(
        "under_section" => "layout-portfolio",
        "type" => "select",
        "name" => "Hover Animation",
		"options" => array('1','2','3','4'),
		"id" => "premiumwd_hover_animation",
        "desc" => "Choose the animation you want to show when user hovers over project.",
        "default" => "1"
        ),
	
	array(
        "under_section" => "layout-portfolio",
        "type" => "select",
	"name" => "Thumbnail Info",
 	"options" => array('Category','Excerpt', 'Any'),
	"id" =>"premiumwd_thumbnail_info",
        "desc" => "Choose the project thumbnail information to display.",
        "default" => "Any"
        ),	
	
	array(
        "under_section" => "layout-portfolio",
        "type" => "select",
	"name" => "Thumbnail Style",
 	"options" => array('Light','Dark'),
	"id" => "premiumwd_thumbnail_style",
        "desc" => "Choose the project thumbnail hover colors.",
        "default" => "Light"
        ),	

	array(
        "under_section" => "layout-portfolio",
	"type" => "small_heading", 
	"title" => "Single Post"
	),
    
	array(
        "under_section" => "layout-portfolio",
        "type" => "checkbox",
  	"default" => array("not"),
	"name" => "Pagination",
 	"options" => array("Yes"), //Required
        "id" => array("premiumwd_portfolio_pagination"),
        "desc" => "Include pagination to navigate to different posts."
	), 


	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Blog",
        "id" => "layout-blog"
    	),

   	array(
        "under_section" => "layout-blog",
        "type" => "text",
        "name" => "Posts per page",
        "id" => "premiumwd_blog_perpage",
        "desc" => "Type how many posts you want to show per page on blog page template, leave blank for none.",
	"default" => "5"
	),   
		
	array(
        "under_section" => "layout-blog",
	"type" => "checkbox",
	"name" => "Pagination",
	"id" => array("premiumwd_blog_pagnation"),        
	"options" => array("Yes"),
        "desc" => "Choose whether you want to show hide pagnation in blog page template.",
	"default" => array("checked")
	),
				
	array(
        "type" => "small_heading",
        "title" => "Post",
        "under_section" => "layout-blog"
    	), 
  

   	array(
        "under_section" => "layout-blog",
	"type" => "checkbox",
	"name" => "Post Tags",
	"id" => array("premiumwd_blog_tags"),        
	"options" => array("Yes"),
        "desc" => "Choose whether you want to show hide tags in single template.",
	"default" => array("checked")
	),

   	array(
        "under_section" => "layout-blog",
	"type" => "checkbox",
	"name" => "Likes",
	"id" => array("premiumwd_blog_likes"),       
	"options" => array("Yes"),
        "desc" => "Choose whether you want to show hide like it in single template.",
	"default" => array("checked")
	),

	array(
        "under_section" => "layout-blog",
        "type" => "checkbox",
  	"default" => array("checked"),
	"name" => "Pagination",
 	"options" => array("Yes"), //Required
        "id" => "premiumwd_single_pagination",
        "desc" => "Include pagination to navigate to different posts.",
	), 


	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Footer",
        "id" => "layout-footer",
    	),
        
	array(
	"under_section" => "layout-footer",
	"type" => "checkbox_image",
	"show_labels" => "false",
	"name" => "Social media",
	"id" => array( 
		   "premiumwd_social_twitter",
		   "premiumwd_social_facebook",
		   "premiumwd_social_linkedin",
		   "premiumwd_social_google-plus",
		   "premiumwd_social_dribbble",
		   "premiumwd_social_youtube",
		   "premiumwd_social_rss",
		   "premiumwd_social_pinterest",
		   "premiumwd_social_skype",
		   "premiumwd_social_instagram",
		   "premiumwd_social_flickr",
		   "premiumwd_social_tumblr",
		   "premiumwd_social_dropbox",
		   "premiumwd_social_foursquare",
		   "premiumwd_social_stack-exchange",
		   "premiumwd_social_weibo",
		   "premiumwd_social_github",
		   "premiumwd_social_envelope"
        	),
        
			"options" => array( 
		   "premiumwd_social_twitter",
		   "premiumwd_social_facebook",
		   "premiumwd_social_linkedin",
		   "premiumwd_social_google-plus",
		   "premiumwd_social_dribbble",
		   "premiumwd_social_youtube",
		   "premiumwd_social_rss",
		   "premiumwd_social_pinterest",
		   "premiumwd_social_skype",
		   "premiumwd_social_instagram",
		   "premiumwd_social_flickr",
		   "premiumwd_social_tumblr",
		   "premiumwd_social_dropbox",
		   "premiumwd_social_foursquare",
		   "premiumwd_social_stack-exchange",
		   "premiumwd_social_weibo",
		   "premiumwd_social_github",
		   "premiumwd_social_envelope"
        	),
			
       	"image_src" => array(
			get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."twitter.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."facebook.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."linkedin.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."google-plus.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."dribbble.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."youtube.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."rss.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."pininterest.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."skype.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."instagram.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."flickr.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."tumblr.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."dropbox.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."foursquare.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."stackexchange.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."weibo.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."github.png",
		   get_bloginfo('stylesheet_directory')."/includes/options/images/icons/"."envelope.png"
			),

	"image_size" => array("30"),    
	"desc" => "Choose which social icons you want to display in footer.",
	"default" => array("not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not", "not")
	),
   
    
    	array(
        "type" => "small_heading",
        "title" => "Social media links",
        "under_section" => "layout-footer"
    	), 
    	
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Twitter",
        "display_checkbox_id" => "premiumwd_social_twitter",
        "id" => "premiumwd_social_twitter_url",
        "placeholder" => "Twitter url",
        "desc" => "Paste url to your Twitter"
	),
           
        array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Facebook",
        "display_checkbox_id" => "premiumwd_social_facebook",
        "id" => "premiumwd_social_facebook_url",
        "placeholder" => "Facebook url",
        "desc" => "Paste url to your Facebook"
	),
                           
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Linkedin",
        "display_checkbox_id" => "premiumwd_social_linkedin",
        "id" => "premiumwd_social_linkedin_url",
        "placeholder" => "Linkedin url",
        "desc" => "Paste url to your Linkedin"
	),    
                
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Google Plus",
        "display_checkbox_id" => "premiumwd_social_google-plus",
        "id" => "premiumwd_social_google-plus_url",
        "placeholder" => "Google Plus url",
        "desc" => "Paste url to your Google Plus"
	),
        	
        array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Dribbble",
        "display_checkbox_id" => "premiumwd_social_dribbble",
        "id" => "premiumwd_social_dribbble_url",
        "placeholder" => "Dribbble url",
        "desc" => "Paste url to your Dribbble"
	),
        				
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Youtube",
        "display_checkbox_id" => "premiumwd_social_youtube",
        "id" => "premiumwd_social_youtube_url",
        "placeholder" => "Youtube url",
        "desc" => "Paste url to your Youtube"
	),
        	
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "RSS",
        "display_checkbox_id" => "premiumwd_social_rss",
        "id" => "premiumwd_social_rss_url",
        "placeholder" => "RSS url",
        "desc" => "Paste url to your RSS"
	),
        	
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Pinterest",
        "display_checkbox_id" => "premiumwd_social_pinterest",
        "id" => "premiumwd_social_pinterest_url",
        "placeholder" => "Pinterest url",
        "desc" => "Paste url to your Pinterest"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Skype",
        "display_checkbox_id" => "premiumwd_social_skype",
        "id" => "premiumwd_social_skype_url",
        "placeholder" => "Skype url",
        "desc" => "Paste url to your Skype"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Instagram",
        "display_checkbox_id" => "premiumwd_social_instagram",
        "id" => "premiumwd_social_instagram_url",
        "placeholder" => "Instagram url",
        "desc" => "Paste url to your Instagram"
	),
        						
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Flickr",
        "display_checkbox_id" => "premiumwd_social_flickr",
        "id" => "premiumwd_social_flickr_url",
        "placeholder" => "Flickr url",
        "desc" => "Paste url to your Flickr"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Tumblr",
        "display_checkbox_id" => "premiumwd_social_tumblr",
        "id" => "premiumwd_social_tumblr_url",
        "placeholder" => "Tumblr url",
        "desc" => "Paste url to your Tumblr"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Dropbox",
        "display_checkbox_id" => "premiumwd_social_dropbox",
        "id" => "premiumwd_social_dropbox_url",
        "placeholder" => "Dropbox url",
        "desc" => "Paste url to your Dropbox"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Foursquare",
        "display_checkbox_id" => "premiumwd_social_foursquare",
        "id" => "premiumwd_social_foursquare_url",
        "placeholder" => "Foursquare url",
        "desc" => "Paste url to your Foursquare"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "stack-exchange",
        "display_checkbox_id" => "premiumwd_social_stack-exchange",
        "id" => "premiumwd_social_stack-exchange_url",
        "placeholder" => "stack-exchange url",
        "desc" => "Paste url to your stack-exchange"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Weibo",
        "display_checkbox_id" => "premiumwd_social_weibo",
        "id" => "premiumwd_social_weibo_url",
        "placeholder" => "Weibo url",
        "desc" => "Paste url to your Weibo"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Github",
        "display_checkbox_id" => "premiumwd_social_github",
        "id" => "premiumwd_social_github_url",
        "placeholder" => "Github url",
        "desc" => "Paste url to your Github"
	),
        			
	array(
        "under_section" => "layout-footer",
        "type" => "text",
        "name" => "Envelope",
        "display_checkbox_id" => "premiumwd_social_envelope",
        "id" => "premiumwd_social_envelope_url",
        "placeholder" => "Envelope url",
        "desc" => "Paste url to your Envelope"
	),
        
	array(
        "section" => "layout",
        "type" => "heading",
        "title" => "Contact",
        "id" => "layout-contact"
    	),
		
	array(
        "under_section" => "layout-contact",
	"type" => "checkbox",
	"name" => "Google Map",
	"id" => "premiumwd_gmap_show",        
	"options" => array("Yes"), //Required
        "desc" => "Choose whether you want to show google map contact page template.",
	"default" => array("not")
	),
    
   	array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "GPS Coordinates",
        "display_checkbox_id" => "premiumwd_gmap_show",
        "default" => '38.898748, -77.037684',
        "id" => "premiumwd_gmap_gps",
        "desc" => "Enter your address in GPS format."
	),

   	array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "GPS Zoom",
        "display_checkbox_id" => "premiumwd_gmap_show",
        "default" => '14',
        "id" => "premiumwd_gmap_zoom",
        "desc" => "Enter your zoom level."
        ),

   	array(
        "under_section" => "layout-contact",
        "type" => "image",
        "display_checkbox_id" => "premiumwd_gmap_show",
       "placeholder" => "http://example.com/marker.png",
        "name" => "Map Marker",
        "id" => "premiumwd_gmap_marker",
        "desc" => "Paste the URL to your map icon",
        "default" => ""
        ),
        	
    	array(
        "under_section" => "layout-contact",
        "type" => "checkbox",
	"name" => "Contact Form",
	"id" => "premiumwd_contact_show",        
	"options" => array("Yes"), //Required
        "desc" => "Choose whether you want to show contact form in contact page template.",
	"default" => array("checked")
	),
    
   	array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "Your e-mail",
        "display_checkbox_id" => "premiumwd_contact_show",
        "default" => get_option('admin_email'),
        "id" => "premiumwd_contact_mail",
        "desc" => "Enter your e-mail, for use in the contact form"
        ),
    
    	array(
        "under_section" => "layout-contact",
        "type" => "text",
        "name" => "E-mail subject",
        "display_checkbox_id" => "premiumwd_contact_show",
        "default" => "Display Theme - Email",
        "id" => "premiumwd_contact_subject",
        "desc" => "Write a subject for received e-mails."
        ),
    
    	array(
        "under_section" => "layout-contact",
        "type" => "textarea",
        "display_checkbox_id" => "premiumwd_contact_show",
        "name" => "E-mail message",
        "default" => "Your message was sent successfully",
        "id" => "premiumwd_contact_message",
        "desc" => "Write a message that will be shown when user sends an e-mail."
        ),
			
	
		
	///////////////////////////////////////
	// Page Settings Close
	///////////////////////////////////////	
    

	
 
 	///////////////////////////////////////
	// Style Settings Open
	///////////////////////////////////////	
	array(
        "type" => "section",
        "icon" => "fa fa-magic",
        "title" => "Style Settings",
        "id" => "style",
        "expanded" => "false"
    	),
	
   	array(
        "section" => "style",
        "type" => "heading",
        "title" => "Typography",
        "id" => "style-typography"
   	),
    	
	array(
	"under_section" => "style-typography", 
	"type" => "small_heading", 
	"title" => "Header"
	), 
				
 	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Logo", 
	"id" => "logo_fontsize", 
	"options" => array('26px','28px', '30px', '32px', '34px', '36px', '38px', '40px'),
	"desc" => "",
	"default" => "30px"
	),

	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Navigation", 
	"id" => "header_nav", 
	"options" => array('12px','13px','14px', '15px', '16px'),
	"desc" => "",
	"default" => "14px"
	),

    	array(
    	"under_section" => "style-typography", 
    	"type" => "small_heading", 
    	"title" => "Sidebar"
    	), 
 
	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Sidebar Titles", 
	"id" => "sidebar_titles", 
	"options" => array('12px','14px', '16px', '18px'),
	"desc" => "",
	"default" => "14px"
	),  

	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Sidebar Text", 
	"id" => "sidebar_text", 
	"options" => array('12px','14px', '16px', '18px'),
	"desc" => "",
	"default" => "12px"
	), 
		
	
    	array(
    	"under_section" => "style-typography", 
    	"type" => "small_heading", 
    	"title" => "Body"
    	), 
	    
 	   array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Page Title", 
	"id" => "page_title_fontsize", 
	"options" => array('26px', '28px', '30px', '32px', '34px', '36px'),
	"desc" => "",
	"default" => "30px"
	),
		
 	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Meta Data", 
	"id" => "meta_data_fontsize", 
	"options" => array('12px', '14px', '16px', '18px'),
	"desc" => "",
	"default" => "16px"
	),
		
	array(
        "under_section" => "style-typography", 
	"type" => "select", 
	"name" => "Font Family", 
	"id" => "body_font_family", 
	"options" => $fontArrays,
	"desc" => "",
	"default" => ""
	),

	
	array(
	"section" => "style",
	"type" => "heading",
	"title" => "Colors",
	"id" => "style-text"
	),
	
	array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Active", 
    	"id" => "body_active", 
   	"default" => "333333"
	),

	array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Active Hover", 
    	"id" => "body_active_hover", 
    	"default" => "0babdb"
	),

    
    	array(
    	"under_section" => "style-text", 
    	"type" => "small_heading", 
    	"title" => "Header"
    	), 

    	array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Title color", 
    	"id" => "title_color", 
    	"default" => "333333"
	),

   	 array(
    	"under_section" => "style-text", 
    	"type" => "color", 
   	 "name" => "Header Background", 
   	 "id" => "header_background", 
   	 "default" => "ffffff"
	),

   	 array(
    	"under_section" => "style-text", 
    	"type" => "small_heading", 
    	"title" => "Side Menu"), 

	 array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Sidemenu Text", 
    	"id" => "sidemenu_text", 
    	"default" => "999999"
	),

	 array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Active", 
    	"id" => "sidemenu_active", 
    	"default" => "ededed"
	),

	 array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Active Hover", 
    	"id" => "sidemenu_active_hover", 
    	"default" => "ffffff"
	),	

    	array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Sidemenu Background", 
    	"id" => "sidemenu_background", 
    	"default" => "262626"
	),
		
	array(
    	"under_section" => "style-text", 
    	"type" => "small_heading", 
    	"title" => "Body"), 
	
	array(
    	"under_section" => "style-text", 
    	"type" => "color", 
    	"name" => "Background", 
    	"id" => "body_background", 
    	"default" => "ededed"
	),
		
	///////////////////////////////////////
	// Style Settings Close
	///////////////////////////////////////	
 	 
	

);
?>
