<?php

/* * ************************************************************************ */
/* * ************************************************************************ */
/*
  /* 	----------------------------------------------------------------------
  /* 						DO NOT EDIT THIS FILE
  /*	----------------------------------------------------------------------
  /*
  /*  			Built by Chris E Rodriguez. http://premiumwd.com
  /*  				Copyright (C) 2012 Premiumwd
  /*
  /************************************************************************** */
/* * ************************************************************************ */

// Make sure we don't expose any info if called directly
if (!function_exists('add_action')) {
    echo 'Hi there!  Not much I can do when called directly.';
    exit;
}

if (!class_exists('Premium_Shortcodes')) :

    class Premium_Shortcodes {

        function __construct() {
            require_once( DIRNAME(__FILE__) . '/theme-shortcodes.php' );

            define('TINYMCE_URI', get_template_directory_uri() . '/includes/shortcodes/tinymce');
            define('TINYMCE_DIR', DIRNAME(__FILE__) . '/includes/shortcodes/tinymce');

            add_action('init', array(&$this, 'action_admin_init'));
            add_action('admin_enqueue_scripts', array(&$this, 'action_admin_scripts_init'));
            add_action('wp_enqueue_scripts', array(&$this, 'action_frontend_scripts'));
        }

        function action_frontend_scripts() {

            $theme_css_url = get_template_directory_uri() . '/includes/shortcodes/css/shortcodes.css';
            $theme_js_url = get_template_directory_uri() . '/includes/shortcodes/js/shortcodes.js';
			wp_enqueue_script('jquery-ui-accordion');
			wp_enqueue_script('jquery-ui-tabs');
            wp_enqueue_style('shortcodes-style', $theme_css_url, false, '1.0', 'all');
            wp_enqueue_script('shortcodes-js', $theme_js_url);
        }

        function action_admin_scripts_init() {

            // css
            wp_enqueue_style('popup', TINYMCE_URI . '/css/popup.css', false, '1.0', 'all');
            wp_enqueue_style('colorpicker', TINYMCE_URI . '/css/colorpicker.css', false, '1.0', 'all');

            // js
            wp_enqueue_script('jquery-ui-sortable');
            wp_enqueue_script('jquery-livequery', TINYMCE_URI . '/js/jquery.livequery.js', false, '1.1.1', false);
            wp_enqueue_script('jquery-appendo', TINYMCE_URI . '/js/jquery.appendo.js', false, '1.0', false);
            wp_enqueue_script('base64', TINYMCE_URI . '/js/base64.js', false, '1.0', false);
            wp_enqueue_script('premium-popup', TINYMCE_URI . '/js/popup.js', false, '1.0', false);
            wp_enqueue_script('jquery-color', TINYMCE_URI . '/js/colorpicker.js', false, '1.0', false);
           wp_localize_script('jquery', 'PremiumShortcodes', array('plugin_folder' => get_template_directory_uri() . '/includes/shortcodes'));
        }

        /**
         * REGISTERS TINYMCE RICH EDITOR BUTTONS
         *
         * @return void
         */
        function action_admin_init() {

            if (!current_user_can('edit_posts') && !current_user_can('edit_pages'))
                return;

            if (get_user_option('rich_editing') == 'true' && is_admin()) {
                add_filter('mce_external_plugins', array(&$this, 'add_rich_plugins'));
                add_filter('mce_buttons', array(&$this, 'register_rich_buttons'));
            }
        }

        // --------------------------------------------------------------------------

        /**
         * Defines TinyMCE rich editor js plugin
         *
         * @return	void
         */
        function add_rich_plugins($plugin_array) {

            $plugin_array['PremiumShortcodes'] = TINYMCE_URI . '/plugin.js';

            return $plugin_array;
        }

        // --------------------------------------------------------------------------

        /**
         * Adds TinyMCE rich editor buttons
         *
         * @return	void
         */
        function register_rich_buttons($buttons) {

            array_push($buttons, "|", 'premium_button');

            return $buttons;
        }

    }

    new Premium_Shortcodes;

endif;
?>